### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'bpython==0.17.1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by quoidautre** [bpython/bpython#1005]
Hi,

On Ubuntu  18.04, and python 3.9.6 (and 3.12.1), I've this error : 
``` 
Traceback (most recent call last):
  File "/usr/bin/bpython-urwid", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/me/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bpython==0.17.1' distribution was not found and is required by the application
``` 

I don't found any help anywhere....

Have you an idea please ?
Thanks
F.

**Comment by sebastinas** [comment]
You seem to be mixing different Python installations. How did you install bpython?
