### ISSUE TITLE
Emoji entered at prompt causes crash

### ISSUE THREAD

**Issue by jimratliff** [bpython/bpython#1018]
When running bpython, I tried to enter the following

message = "✅"

This character is: ✅
check mark symbol
Unicode: U+2705, UTF-8: E2 9C 85

But as soon as I entered the emoji itself (without the closing quote or return): I fot:

```
>>> message = "✅
Traceback (most recent call last):
  File "<REDACTED_PATH>/venv/bin/bpython", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "<REDACTED_PATH>/venv/lib/python3.11/site-packages/bpython/curtsies.py", line 248, in main
    repl.mainloop(True, paste)
  File "<REDACTED_PATH>/venv/lib/python3.11/site-packages/bpython/curtsies.py", line 181, in mainloop
    self.process_event_and_paint(e)
  File "<REDACTED_PATH>/venv/lib/python3.11/site-packages/bpython/curtsies.py", line 151, in process_event_and_paint
    array, cursor_pos = self.paint()
                        ^^^^^^^^^^^^
  File "<REDACTED_PATH>/venv/lib/python3.11/site-packages/bpython/curtsiesfrontend/repl.py", line 1762, in paint
    assert cursor_row >= 0 and cursor_column >= 0, (
                               ^^^^^^^^^^^^^^^^^^
AssertionError: (-1, 153, '>>> message = "✅', 'message = "✅', 12)
```

In contrast, no problem occurs when I enter the same text into the standard python interpreter.

**Comment by sebastinas** [comment]
I cannot reproduce the issue. Are all your dependencies up to date?
