### ISSUE TITLE
Interpreter.showsyntaxerror() got an unexpected keyword argument 'source' with Python 3.13

### ISSUE THREAD

**Issue by evgeni** [bpython/bpython#1025]
Ohai,

running both 0.24 and 0.25.dev44 (b6318376b255be645b16aaf27c6475359e384ab9) on Python 3.13, a "trivial" syntax error kills bpython:

```
bpython version 0.25.dev44 on top of Python 3.13.0 /tmp/tmp.CIgBklNxhg/venv13/bin/python3.13
>>> list(None || [])
Traceback (most recent call last):
  File "/usr/lib64/python3.13/code.py", line 65, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib64/python3.13/codeop.py", line 152, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib64/python3.13/codeop.py", line 74, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
  File "/usr/lib64/python3.13/codeop.py", line 117, in __call__
    codeob = compile(source, filename, symbol, flags, True)
  File "<bpython-input-3>", line 1
    list(None || [])
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmp.CIgBklNxhg/venv13/bin/bpython", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsies.py", line 245, in main
    repl.mainloop(True, paste)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsies.py", line 178, in mainloop
    self.process_event_and_paint(e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsies.py", line 138, in process_event_and_paint
    self.process_event(e)
    ~~~~~~~~~~~~~~~~~~^^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 660, in process_event
    self.process_key_event(e)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 800, in process_key_event
    self.on_enter()
    ~~~~~~~~~~~~~^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 968, in on_enter
    self.push(self.current_line, insert_into_history=new_code)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1308, in push
    self.run_code_and_maybe_finish()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1311, in run_code_and_maybe_finish
    r = self.coderunner.run_code(for_code=for_code)
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 138, in run_code
    request = self.code_context.switch()
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 185, in _blocking_run_code
    unfinished = self.interp.runsource(self.source)
  File "/tmp/tmp.CIgBklNxhg/venv13/lib64/python3.13/site-packages/bpython/repl.py", line 153, in runsource
    return super().runsource(source, filename, symbol)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/code.py", line 68, in runsource
    self.showsyntaxerror(filename, source=source)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Interpreter.showsyntaxerror() got an unexpected keyword argument 'source'
```

On 3.12 the same works just fine:
```
bpython version 0.25.dev44 on top of Python 3.12.7 /tmp/tmp.CIgBklNxhg/venv12/bin/python3.12
>>> list(None || [])
  File "<input>", line 1
    list(None || [])
               ^
SyntaxError: invalid syntax
>>> 
```

**Comment by sebastinas** [comment]
With bbdff64fe37b851b6a33183a6a35739bbb4687a0 it should no longer die with an exception. At some point we should also handle the new (undocumented) `source` argument.

**Comment by evgeni** [comment]
aye, it doesn't crash anymore, thanks!

**Comment by prawnydagrate** [comment]
I got the same crash:
```py
bpython version 0.24 on top of Python 3.13.0 /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
>>> from typing import Any
>>> def l2t(l: list[Any]) -> tuple[Any, ...]:
...     return tuple(el for el in l if not isinstance(el, list) else l2t(el))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/code.py", line 65, in runsource
    code = self.compile(source, filename, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/codeop.py", line 152, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/codeop.py", line 74, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/codeop.py", line 117, in __call__
    codeob = compile(source, filename, symbol, flags, True)
  File "<bpython-input-5>", line 2
    return tuple(el for el in l if not isinstance(el, list) else l2t(el))
                                                            ^^^^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/bin/bpython", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsies.py", line 248, in main
    repl.mainloop(True, paste)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsies.py", line 178, in mainloop
    self.process_event_and_paint(e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsies.py", line 141, in process_event_and_paint
    self.process_event(e)
    ~~~~~~~~~~~~~~~~~~^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 660, in process_event
    self.process_key_event(e)
    ~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 800, in process_key_event
    self.on_enter()
    ~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 969, in on_enter
    self.push(self.current_line, insert_into_history=new_code)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1309, in push
    self.run_code_and_maybe_finish()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1312, in run_code_and_maybe_finish
    r = self.coderunner.run_code(for_code=for_code)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 138, in run_code
    request = self.code_context.switch()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 185, in _blocking_run_code
    unfinished = self.interp.runsource(self.source)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bpython/repl.py", line 153, in runsource
    return super().runsource(source, filename, symbol)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/code.py", line 68, in runsource
    self.showsyntaxerror(filename, source=source)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Interpreter.showsyntaxerror() got an unexpected keyword argument 'source'
```

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpython/bpython/issues/1025#event-15948637129

#### Reproduction

1.	~~~py
	#!/usr/bin/env python3.13
	import PyQt6.QtWidgets
	return PyQt6.QtWidgets.QStyleFactory.keys()[0]
	~~~

1.	<blockquote>

	~~~py
	bpython version 0.24 on top of Python 3.13.2 /usr/bin/python3
	>>> import PyQt6.QtWidgets
	>>> PyQt6.QtWidgets.QStyleFactory.keys()[0]
	'Breeze'
	>>> return PyQt6.QtWidgets.QStyleFactory.keys()[0]
	Traceback (most recent call last):
	  File "/usr/lib64/python3.13/code.py", line 65, in runsource
	    code = self.compile(source, filename, symbol)
	  File "/usr/lib64/python3.13/codeop.py", line 155, in __call__
	    return _maybe_compile(self.compiler, source, filename, symbol)
	  File "/usr/lib64/python3.13/codeop.py", line 75, in _maybe_compile
	    return compiler(source, filename, symbol, incomplete_input=False)
	  File "/usr/lib64/python3.13/codeop.py", line 118, in __call__
	    codeob = compile(source, filename, symbol, flags, True)
	  File "<bpython-input-5>", line 1
	SyntaxError: 'return' outside function

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/bin/bpython", line 33, in <module>
	    sys.exit(load_entry_point('bpython==0.24', 'console_scripts', 'bpython')())
	             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsies.py", line 248, in main
	    repl.mainloop(True, paste)
	    ~~~~~~~~~~~~~^^^^^^^^^^^^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsies.py", line 181, in mainloop
	    self.process_event_and_paint(e)
	    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsies.py", line 141, in process_event_and_paint
	    self.process_event(e)
	    ~~~~~~~~~~~~~~~~~~^^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 660, in process_event
	    self.process_key_event(e)
	    ~~~~~~~~~~~~~~~~~~~~~~^^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 800, in process_key_event
	    self.on_enter()
	    ~~~~~~~~~~~~~^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 969, in on_enter
	    self.push(self.current_line, insert_into_history=new_code)
	    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1309, in push
	    self.run_code_and_maybe_finish()
	    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/repl.py", line 1312, in run_code_and_maybe_finish
	    r = self.coderunner.run_code(for_code=for_code)
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 138, in run_code
	    request = self.code_context.switch()
	  File "/usr/lib/python3.13/site-packages/bpython/curtsiesfrontend/coderunner.py", line 185, in _blocking_run_code
	    unfinished = self.interp.runsource(self.source)
	  File "/usr/lib/python3.13/site-packages/bpython/repl.py", line 153, in runsource
	    return super().runsource(source, filename, symbol)
	           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib64/python3.13/code.py", line 68, in runsource
	    self.showsyntaxerror(filename, source=source)
	    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
	TypeError: Interpreter.showsyntaxerror() got an unexpected keyword argument 'source'
	~~~

	</blockquote>

	[^1]

	[^1]: [`app.warp.dev/block/z0UGeOpUGkj8i833n9iENv`](https://app.warp.dev/block/z0UGeOpUGkj8i833n9iENv)

#### Environment

1.	~~~sh
	#!/usr/bin/env sh
	dnf info python3-bpython
	~~~

1.	<blockquote>

	~~~YAML
	Updating and loading repositories:
	Repositories loaded.
	Installed packages
	Name            : python3-bpython
	Epoch           : 0
	Version         : 0.24
	Release         : 9.fc41
	Architecture    : noarch
	Installed size  : 1.8 MiB
	Source          : bpython-0.24-9.fc41.src.rpm
	From repository : fedora
	Vendor          : Fedora Project
	~~~

	</blockquote>

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpython/bpython/issues/1025#issuecomment-2649571866

Ah, apologies - missed that [it was set to `0.25`](https://github.com/bpython/bpython/issues/1025#event-15948634701).
