### ISSUE TITLE
ANSI escape sequence support in bpython-curtsies

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#340]
I thought we had this somewhere, but I can't find it.

```
from curtsies.fmtuncs import *
print blue('a'*200)   # assuming terminal width is < 80 or so
```

This isn't just curtsies, it's ANSI escape sequences of any kind correctly - we should find a library that parses them and strips them at the minimum, or better that converts them to curtsies colored strings. Curtsies has a parser for this but either we're not useing it or it doesn't quite work right.

**Comment by sebastinas** [comment]
The long string does not work because it is actually invalid. The last `\x1b[` is incomplete.

**Comment by thomasballinger** [comment]
it'd be nice not to crash though I think was the issue

On Fri, Jan 9, 2015 at 2:24 PM, Sebastian Ramacher <notifications@github.com

**Comment by thomasballinger** [comment]
The curtsies parser should have a fallback mode, or this error should be caught and an version stripped of control characters displayed.

~~~.py
>>> s = "\x1b[31m\x1b[1mAttributeError\x1b[0m\x1b[39m: \x1b[36m'Game' object has no attribute 'bodies'\x1b["
>>> print s
AttributeError: 'Game' object has no attribute 'bodies'
Traceback (most recent call last):
  File "/Users/tomb/.virtualenvs/bpython/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.13-321', 'console_scripts', 'bpython')()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 69, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 133, in mainloop
    process_event(e)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 119, in process_event
    array, cursor_pos = repl.paint()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 1089, in paint
    history = paint.paint_history(current_line_start_row, width, self.lines_for_display)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/replpainter.py", line 33, in paint_history
    lines.append(fmtstr(line[:columns]))
  File "/Users/tomb/.virtualenvs/bpython/lib/python2.7/site-packages/curtsies/formatstring.py", line 510, in fmtstr
    string = FmtStr.from_str(string)
  File "/Users/tomb/.virtualenvs/bpython/lib/python2.7/site-packages/curtsies/formatstring.py", line 138, in from_str
    tokens_and_strings = parse(s)
  File "/Users/tomb/.virtualenvs/bpython/lib/python2.7/site-packages/curtsies/escseqparse.py", line 32, in parse
    raise ValueError("Can't parse escape sequence: %r %r %r %r" % (s, repr(front), token, repr(rest)))
ValueError: Can't parse escape sequence: "\x1b[31m\x1b[1mAttributeError\x1b[0m\x1b[39m: \x1b[36m'Game' object has no attribute 'bodies'\x1b[" '"\'Game\' object has no attribute \'bodies\'"' {'csi': '\x1b', 'command': '[', 'seq': '\x1b['} "''"
~~~

**Comment by lilydjwg** [comment]
I can't use tornado's nice log formatter for this reason:

```
ValueError: Can't parse escape sequence: '\x1b[32m[I 03-12 15:11:33.683 <input>:1]\x1b[m\x0f test' "'[I 03-12 15:11:33.683 <input>:1]'" {'intermed': '', 'csi': '\x1b[', 'seq': '\x1b[m', 'private': '', 'numbers': [], 'command': 'm'} "'\\x0f test'"
```

**Comment by thomasballinger** [comment]
This is fixed on master in Curtsies by https://github.com/thomasballinger/curtsies/commit/6f6ba212fd3185bcbb0dd1728274fa34fa154925 but there hasn't been a new release of Curtsies yet, I'll make one soon.
