### ISSUE TITLE
error report from irc

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#406]
http://ix.io/eIp

**Comment by sebastinas** [comment]
autocompletion with non-ascii filesnames works fine here. We need a way to reproduce the issue.

In case the content of the URL disappears:

```pytb
Traceback (most recent call last):
  File "/usr/bin/bpython-curtsies", line 9, in <module>
    load_entry_point('bpython==mercurial', 'console_scripts', 'bpython-curtsies')()
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 66, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 139, in mainloop
    process_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 120, in process_event
    repl.process_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 407, in process_event
    return self.process_key_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 518, in process_key_event
    self.add_normal_character(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 700, in add_normal_character
    self.current_line[self.cursor_offset:])
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 1154, in _set_current_line
    self.update_completion()
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 730, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/lib/python3.4/site-packages/bpython/repl.py", line 645, in complete
    self.config.complete_magic_methods)
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 80, in get_completer
    matches = completer.matches(cursor_offset, current_line, **kwargs)
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 150, in matches
    for filename in glob(os.path.expanduser(text + '*')):
  File "/usr/lib/python3.4/glob.py", line 18, in glob
    return list(iglob(pathname))
  File "/usr/lib/python3.4/glob.py", line 49, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/python3.4/glob.py", line 68, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python3.4/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/usr/lib/python3.4/functools.py", line 452, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib/python3.4/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.4/sre_parse.py", line 746, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.4/sre_parse.py", line 504, in _parse
    raise error("bad character range")
sre_constants.error: bad character range
```

**Comment by sebastinas** [comment]
Let's close this until we have a way to reproduce it.
