### ISSUE TITLE
bpython-curtsies crashes if no readline history on enter

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#432]
I think this is if you don't have a ~/.pythonhist file.

**Comment by thomasballinger** [comment]
~~~.py
Traceback (most recent call last):
  File "/usr/local/bin/bpython-curtsies", line 9, in <module>
    load_entry_point('bpython==0.13.1', 'console_scripts', 'bpython-curtsies')()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 60, in main
    mainloop(config, locals_, banner, interp, paste)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 92, in mainloop
    process_event(term.get_annotated_event(idle=find_iterator))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 76, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 341, in process_event
    self.on_enter()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 374, in on_enter
    self.rl_history.last()
  File "/usr/local/lib/python2.7/site-packages/bpython/repl.py", line 241, in last
    return self.entries[0]
IndexError: list index out of range
~~~

**Comment by thomasballinger** [comment]
would also be good to check if this happens with bpython as well

**Comment by sebastinas** [comment]
It does not happen with bpython.cli.

**Comment by sebastinas** [comment]
Now fixed.
