### ISSUE TITLE
edit_config hotkey does not work

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#436]
Wihle testing the `edit_config` hotkey:

```python
python -m bpython.curtsies
bpython version 0.13-314 on top of Python 2.7.9 /usr/bin/python
>>> 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sebastian/development/bpython/bpython/curtsies.py", line 136, in <module>
    sys.exit(main())
  File "/home/sebastian/development/bpython/bpython/curtsies.py", line 69, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/home/sebastian/development/bpython/bpython/curtsies.py", line 130, in mainloop
    process_event(e)
  File "/home/sebastian/development/bpython/bpython/curtsies.py", line 112, in process_event
    repl.process_event(e)
  File "bpython/curtsiesfrontend/repl.py", line 452, in process_event
    return self.process_control_event(e)
  File "bpython/curtsiesfrontend/repl.py", line 466, in process_control_event
    self.status_bar.process_event(e)
  File "bpython/curtsiesfrontend/interaction.py", line 70, in process_event
    if isinstance(e, events.RefreshRequestEvent):
AttributeError: 'module' object has no attribute 'RefreshRequestEvent'
```

**Comment by thomasballinger** [comment]
There are two different sets of event classes - one in the curtsies library (https://github.com/thomasballinger/curtsies/blob/master/curtsies/events.py) and one in bpython.curtsiesfrontend.events. It appears there's been some confusion between them, hence the error above.
