### ISSUE TITLE
crash on open paren

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#440]
Somewhere in autocomplete docstrings and names are getting set to the functions themselves instead of text? Almost certainly introduced by my recent autocompletion refactor.
~~~.py
tom-mba:~ tomb$ bpython
bpython version mercurial on top of Python 2.7.9 /usr/local/opt/python/bin/python2.7
>>> a = 1.0
>>> a.as_integer_ratio
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.13.post323', 'console_scripts', 'bpython')()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 69, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 133, in mainloop
    process_event(e)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 119, in process_event
    array, cursor_pos = repl.paint()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 1134, in paint
    self.matches_iter.completer.format if self.matches_iter.completer else None)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/replpainter.py", line 154, in paint_infobox
    (formatted_docstring(docstring, width, config) if docstring else []))
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/replpainter.py", line 145, in formatted_docstring
    for line in docstring.split('\n')), [])
AttributeError: 'builtin_function_or_method' object has no attribute 'split'
~~~

**Comment by thomasballinger** [comment]
Not an issue, I was using the wrong branch (which is obvious now, because of the great autoversioning!)
