### ISSUE TITLE
Crash on multiline rewind of line containing opening and closing parens

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#448]
~~~.py
>>> for line in f:
...        a() |
Traceback (most recent call last):
  File "/Users/tomb/.virtualenvs/bpython/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.13-363', 'console_scripts', 'bpython')()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 69, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 147, in mainloop
    process_event(e)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsies.py", line 126, in process_event
    repl.process_event(e)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 436, in process_event
    return self.process_key_event(e)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 540, in process_key_event
    self.undo()
  File "/Users/tomb/Dropbox/code/bpython/bpython/repl.py", line 802, in undo
    self.take_back_buffer_line()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 1276, in take_back_buffer_line
    self._set_cursor_offset(0, update_completion=False)
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 1246, in _set_cursor_offset
    self.unhighlight_paren()
  File "/Users/tomb/Dropbox/code/bpython/bpython/curtsiesfrontend/repl.py", line 887, in unhighlight_paren
    self.display_buffer[lineno] = self.display_buffer[lineno].setslice_with_length(0, len(new), new, len(self.display_buffer[lineno]))
IndexError: list index out of range
~~~
where | is the cursor.

**Comment by thomasballinger** [comment]
It seems like this could be fixed by simultaneously changing cursor_offset and current_line - or cleverly changing them in an order than makes sense. The former is probably more sustainable, maybe making these both properties was a bad idea in the first place.

`set_line_and_cursor` maybe, or `set_line_with_cursor`

**Comment by thomasballinger** [comment]
Fixed, but the real solution here is a method that sets `cursor_offset` and `curent_line` together
