### ISSUE TITLE
Dictionary key completion fails in 2.6

### ISSUE THREAD

**Issue by maryakins** [bpython/bpython#458]
```
ERROR: test_set_of_keys_returned_when_matches_found (bpython.test.test_autocomplete.TestDictKeyCompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bpython/bpython/build/lib/bpython/test/test_autocomplete.py", line 161, in test_set_of_keys_returned_when_matches_found
    result=com.matches(2,"d[" , local)
  File "/home/travis/build/bpython/bpython/build/lib/bpython/autocomplete.py", line 223, in matches
    return set("{!r}".format(k) for k in obj.keys()
  File "/home/travis/build/bpython/bpython/build/lib/bpython/autocomplete.py", line 224, in <genexpr>
    if repr(k).startswith(orig))
ValueError: zero length field name in format
```

**Comment by sebastinas** [comment]
Thanks for finding this issue. It only happens with Python 2.6 and can be fixed by using `{0!r}` instead.
