### ISSUE TITLE
RefreshRequestEvent when pasting indented lines

### ISSUE THREAD

**Issue by davoclavo** [bpython/bpython#476]
If you paste 2 or more indented lines, bpython throws an error:
e.g.
```
    pass
    pass
```
```sh
❯❯❯ bpython                                                                                                                       ⏎
bpython version 0.13-342 on top of Python 2.7.8 /usr/local/opt/python/bin/python2.7
>>>
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.13-342', 'console_scripts', 'bpython')()
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsies.py", line 69, in main
    mainloop(config, locals_, banner, interp, paste, interactive=(not exec_args))
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsies.py", line 145, in mainloop
    process_event(e)
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsies.py", line 124, in process_event
    repl.process_event(e)
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsiesfrontend/repl.py", line 438, in process_event
    return self.process_control_event(e)
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsiesfrontend/repl.py", line 473, in process_control_event
    self.process_simple_keypress(ee)
  File "/Users/davidgu/dev/hackerschool/py/bpython/bpython/curtsiesfrontend/repl.py", line 693, in process_simple_keypress
    self.process_event(events.RefreshRequestEvent())
AttributeError: 'module' object has no attribute 'RefreshRequestEvent'
```

**Comment by sebastinas** [comment]
This should be fixed for a long time now. master is about 250 commits newer than 0.13-342.

**Comment by thomasballinger** [comment]
Hooray for the startup banner! It was sebastina's idea to add if I remember correctly.

**Comment by davoclavo** [comment]
I realized I had installing my own old fork of bpython. I now have 0.13-622 and it is indeed fixed. Thanks and sorry for the mistake :)
