### ISSUE TITLE
import broken for non-ascii names

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#487]
Python 2 with curtsies:

```pycon
>>> __import__('fð')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/sebastian/development/bpython/bpython/curtsiesfrontend/repl.py", line 428, in new_import
    fromlist=fromlist, level=level)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf0' in position 1: ordinal not in range(128)
```

This works in Python 3 with curtsies and in plain Python 2.

**Comment by thomasballinger** [comment]
Is this fixed? I can't replicate it.

**Comment by sebastinas** [comment]
No, it's not.

**Comment by sebastinas** [comment]
Oh, that might be coupled to watchdog being available.

**Comment by sebastinas** [comment]
Better traceback:
```pytb
>>> __import__('fð')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/sebastian/development/bpython/bpython/curtsiesfrontend/coderunner.py", line 200, in write
    self.on_write(*args, **kwargs)
  File "/home/sebastian/development/bpython/bpython/curtsiesfrontend/repl.py", line 1002, in send_to_stdout
    lines = output.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```

**Comment by thomasballinger** [comment]
`print 'fð'` also triggers this.

**Comment by thomasballinger** [comment]
https://github.com/bpython/bpython/commit/ff08e62fb8cc5cc9ea3f78a65f4d812bd7bd8c78 fixes these, but I'd like to hear what people think of it.

**Comment by thomasballinger** [comment]
This has been merged.
