### ISSUE TITLE
bpython (master) dies on input

### ISSUE THREAD

**Issue by amorozov** [bpython/bpython#491]
After upgrading to the most recent commit from master I've got the following, just right on the first line, when tried to issue `s='a[a.l-1]'`:

    (Tests)alex@rhyme ~/work/DispatchersTests $ bpython
    bpython version 0.15.dev49 on top of Python 2.7.8 /home/work/users/alex/DispatchersTests/Tests/bin/python
    >>> s = 'a[a.l-1
    Traceback (most recent call last):
      File "/home/work/users/alex/DispatchersTests/Tests/bin/bpython", line 9, in <module>
        load_entry_point('bpython==0.15.dev49', 'console_scripts', 'bpython')()
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 81, in main
        interactive=(not exec_args))
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 182, in mainloop
        process_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 140, in process_event
        repl.process_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 530, in process_event
        return self.process_key_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 671, in process_key_event
        self.add_normal_character(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 890, in add_normal_character
        self.cursor_offset += 1
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1405, in _set_cursor_offset
        self.update_completion()
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 920, in update_completion
        self.list_win_visible = BpythonRepl.complete(self, tab)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/repl.py", line 605, in complete
        history=self.history)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/autocomplete.py", line 472, in get_completer_bpython
        return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/autocomplete.py", line 452, in get_completer
        cursor_offset, line, **kwargs)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/autocomplete.py", line 171, in matches
        for filename in glob(os.path.expanduser(text + '*')):
      File "/usr/lib64/python2.7/glob.py", line 27, in glob
        return list(iglob(pathname))
      File "/usr/lib64/python2.7/glob.py", line 44, in iglob
        for name in glob1(os.curdir, basename):
      File "/usr/lib64/python2.7/glob.py", line 78, in glob1
        return fnmatch.filter(names, pattern)
      File "/home/work/users/alex/DispatchersTests/Tests/lib64/python2.7/fnmatch.py", line 54, in filter
        _cache[pat] = re.compile(res)
      File "/home/work/users/alex/DispatchersTests/Tests/lib64/python2.7/re.py", line 190, in compile
        return _compile(pattern, flags)
      File "/home/work/users/alex/DispatchersTests/Tests/lib64/python2.7/re.py", line 244, in _compile
        raise error, v # invalid expression
    sre_constants.error: bad character range

bpython: 5880f85d87498c4ebd65ca6d18d43196845dee08
curtsies (0.2.2)

**Comment by amorozov** [comment]
Unfortunately these changes (up to 601df715e0d062050c8a4687aaebce03aed7b4f5) haven't helped with the issue

**Comment by sebastinas** [comment]
I've re-introduced the issue in 601df715e0d062050c8a4687aaebce03aed7b4f5. It should be working again in 77506c1208febc0f93b05f9aff07b8f8d6ed5ae8.
