### ISSUE TITLE
crash with "TypeError: 'classmethod' object is not callable"

### ISSUE THREAD

**Issue by cym13** [bpython/bpython#498]
Here is all I have:

$ /usr/bin/bpython
bpython version 0.14.1 on top of Python 3.4.3 /usr/bin/python
\>\>\>from fractions import Fraction
\>\>\>
Traceback (most recent call last):
  File "/usr/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.14.1', 'console_scripts', 'bpython')()
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 488, in process_event
    return self.process_key_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_key_event
    self.add_normal_character(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/lib/python3.4/site-packages/bpython/repl.py", line 599, in complete
    history=self.history)
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 466, in get_completer_bpython
    return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 446, in get_completer
    cursor_offset, line, **kwargs)
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 306, in matches
    matches.add(_callable_postfix(val, word))
  File "/usr/lib/python3.4/site-packages/bpython/autocomplete.py", line 536, in _callable_postfix
    if inspection.is_callable(value):
  File "/usr/lib/python3.4/site-packages/bpython/inspection.py", line 279, in is_callable
    return isinstance(obj, collections.Callable)
  File "/usr/lib/python3.4/abc.py", line 191, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/usr/lib/python3.4/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
TypeError: 'classmethod' object is not callable

EDIT: I should precise that it didn't crash right after evaluating the expressions but when I typed another letter.

**Comment by thomasballinger** [comment]
I can reproduce, type "F" on the next line.

**Comment by thomasballinger** [comment]
This is fixed by fcd18378d7c67ef7f791dd4ecdb301174cc8dc2a in master

**Comment by thomasballinger** [comment]
I assume 0.14 doesn't support 3.1 (which this commit removes some support for) and so going to apply this to a 0.14 bugfix.

**Comment by thomasballinger** [comment]
Fixed by e3e9061e7afb76a72aa033648ccc1cc5fa9fecec in 0.14-bugfix, already fixed in master
