### ISSUE TITLE
bpython doesn't start under pypy3

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#502]
This is fixed by https://bitbucket.org/pypy/pypy/commits/d8475a6257bc which is a patch one could apply themselves to their local copy of pypy3.

**Comment by Rnhmjoj** [comment]
I have found another problem with pypy3:

     bpython version 0.14.1 on top of Python 3.2.5 /usr/local/opt/pyenv/versions/pypy3-2.4.0/bin/python
     debug: OperationError:
     debug:  operror-type: TypeError
     debug:  operror-value: unsupported operand type(s) for +: 'int' and 'NoneType'

Which seems to be caused by this:
      File "/usr/local/opt/pyenv/versions/pypy3-2.4.0/lib_pypy/_curses.py", line 1360, in tigetstr
        val = lib.tigetstr(capname)
    TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

Anyway I don't understand how the debug works: adding a print to debug cause an infinite loop. I had to remove `sys.stdout = self.stdout` in `repl.py` to see what was going on. How do I view the log?

**Comment by Rnhmjoj** [comment]
I solved adding
```py
if isinstance(capname, str):
    capname = capname.encode('utf-8')
```
in `lib_pypy/_curses.py` at line 1360.

**Comment by Rnhmjoj** [comment]
One more thing. 

To avoid [these](http://hastebin.com/puqacopusa.py) errors you should replace
```py
__builtins__['__import__']
```
with 
```py
__builtins__.__import__
```

**Comment by thomasballinger** [comment]
Thanks for reporting these! To use debug logging, run bpython with the logging flag, as in

    $ bpython -LL

and then use `logger.debug(something)` and look for something in a file called `bpython.log`.

I've posted the pypy bug (https://bitbucket.org/pypy/pypy/issue/1997/pypy3-cursestigetstr-raises-ctype) and made your fix on a fork.

We've already gotten rid of the `__builtins__['__import__']` issue in master, and probably won't be fixing it in bpython 0.14, since we don't officially support pypy yet.

**Comment by Rnhmjoj** [comment]
Great! Thanks for the explanation.

**Comment by thomasballinger** [comment]
TODO: figure out the current status of the the pypy patch above - it's not complete, and/or ask #pypy about it.

**Comment by OOPMan** [comment]
This is happening for me with PyPy2 as well:

```
(recomed-pypy-2.5.0-kubuntu) adamj@Harvester  ~/Development/SpringLab/Python/recomed/backend   staging-issue-30 ●  bpython
bpython version 0.14.1 on top of Python 2.7.9 /home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-2.5.0-kubuntu/bin/pypy

debug: OperationError:
debug:  operror-type: TypeError
debug:  operror-value: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by Trundle** [comment]
With the latest pypy3 release (PyPy3.3 v5.5-alpha), bpython starts and at least the curtsies frontend seems to be usable. 

The curses frontend throws an exception unfortunately, for example when pressing the backspace key:

```
Traceback (most recent call last):
  File "/tmp/bpython/pypy3-v5.5.0-linux64/lib-python/3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/tmp/bpython/pypy3-v5.5.0-linux64/lib-python/3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./bpython/cli.py", line 1977, in <module>
    sys.exit(main())
  File "./bpython/cli.py", line 1963, in main
    banner=banner)
  File "./bpython/cli.py", line 1845, in curses_wrapper
    return func(stdscr, *args, **kwargs)
  File "./bpython/cli.py", line 1930, in main_curses
    exit_value = clirepl.repl()
  File "./bpython/cli.py", line 1127, in repl
    inp = self.get_line()
  File "./bpython/cli.py", line 671, in get_line
    key = self.get_key()
  File "./bpython/cli.py", line 612, in get_key
    key += self.scr.getkey()
TypeError: unsupported operand type(s) for +: 'str' and 'bytes'
```
