### ISSUE TITLE
os.waitpid that never ends with "sh" library

### ISSUE THREAD

**Issue by cym13** [bpython/bpython#512]
Hi,

Here is the stackstrace:

    $ /usr/bin/bpython
    
    bpython version 0.14.1 on top of Python 3.4.3 /usr/bin/python
    >>> from sh import ls, cat
    >>> ls()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/sh.py", line 769, in __call__
        return RunningCommand(cmd, call_args, stdin, stdout, stderr)
      File "/usr/lib/python3.4/site-packages/sh.py", line 330, in __init__
        self.wait()
      File "/usr/lib/python3.4/site-packages/sh.py", line 334, in wait
        self._handle_exit_code(self.process.wait())
      File "/usr/lib/python3.4/site-packages/sh.py", line 1152, in wait
        pid, exit_code = os.waitpid(self.pid, 0)
    InterruptedError: [Errno 4] Interrupted system call
    >>> cat("./test.py")
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/sh.py", line 769, in __call__
        return RunningCommand(cmd, call_args, stdin, stdout, stderr)
      File "/usr/lib/python3.4/site-packages/sh.py", line 330, in __init__
        self.wait()
      File "/usr/lib/python3.4/site-packages/sh.py", line 334, in wait
        self._handle_exit_code(self.process.wait())
      File "/usr/lib/python3.4/site-packages/sh.py", line 1152, in wait
        pid, exit_code = os.waitpid(self.pid, 0)
    InterruptedError: [Errno 4] Interrupted system call

Each call to a function imported through sh never ends, the previous
exceptions were thrown only when I forced it to flush by resizing the window.
The same lines were tested with python3 and ipython3 without problem.

It may be of importance to know my system:

$ uname -a
Linux Eather 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux

**Comment by sebastinas** [comment]
This might be a consequence of using greenlets. The old curses interface does not show this behavior.

**Comment by jquast** [comment]
> The same lines were tested with python3 and ipython3 without problem.

All python functions using system calls now gracefully retry when interrupted in python3.5, pep-475: https://www.python.org/dev/peps/pep-0475/

The only fix would be upstream sh.py module, to wrap os.waitpid with ``while True`` loop, continuing on ``InterruptedError``, ``break``ing otherwise.

**Comment by jquast** [comment]
Also window resizes cause a system call (``SIGWINCH``), this is why ``os.waitpid`` is interrupted.
