### ISSUE TITLE
got a crash on re-evaluating script after edit it in the external editor

### ISSUE THREAD

**Issue by amorozov** [bpython/bpython#514]
Traceback (most recent call last):
      File "/home/work/users/alex/DispatchersTests/Tests/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.15.dev65', 'console_scripts', 'bpython')()
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 81, in main
        interactive=(not exec_args))
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 182, in mainloop
        process_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsies.py", line 140, in process_event
        repl.process_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 530, in process_event
        return self.process_key_event(e)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 660, in process_key_event
        self.send_session_to_external_editor()
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 845, in send_session_to_external_editor
        self.reevaluate(insert_into_history=True)
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1490, in reevaluate
        logger.debug('old_display_lines_offscreen %s', '|'.join(str(x) for x in old_display_lines_offscreen))
      File "/home/work/users/alex/DispatchersTests/Tests/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1490, in <genexpr>
        logger.debug('old_display_lines_offscreen %s', '|'.join(str(x) for x in old_display_lines_offscreen))
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

Python-2.7.8, BPython 0.15.dev65

The code I evaluated is a valid Python code with some string values with Cyrillic characters. The current locale is ru_RU.UTF-8.

**Comment by sebastinas** [comment]
Could you tell us what the input looked liked? I copied the whole Cyrillic alphabet into the editor session and bpython didn't crash afterwards.

Which editor are you using?

**Comment by sebastinas** [comment]
Closing until more info is supplied.
