### ISSUE TITLE
pkg_resources.DistributionNotFound: pyasn1

### ISSUE THREAD

**Issue by dslackw** [bpython/bpython#516]
Hi,
I am the maintainer for bpython on Slackware Linux from slackbuilds.org [bpython]( http://slackbuilds.org/repository/14.1/development/bpython) and trying to update the version 1.14.1.
After run it seems that new modules required.

Traceback (most recent call last):
  File "/usr/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyasn1

**Comment by sebastinas** [comment]
This is documented. From README.md:

```
If you are using Python 2 before 2.7.7, the following dependency is also required:

 * requests[security]
```

`requests[security]` depends on `pyasn1` and some other packages.

**Comment by dslackw** [comment]
Ok thank you !
