### ISSUE TITLE
Escape sequences are being changed, issue with Blessings compatibility?

### ISSUE THREAD

**Issue by keyan** [bpython/bpython#518]
(@thomasballinger On the topic of escape codes...)

I was playing with Blessings and I got this strange error, here is the full session:

````
Keyan:~ Keyan$ bpython
bpython version 0.14.1 on top of Python 2.7.9 /usr/local/opt/python/bin/python2.7
>>> from blessings import Terminal
>>> term = Terminal()
>>> print term.red("TESTING")
TESTING
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 145, in process_event
    array, cursor_pos = repl.paint()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1181, in paint
    history = paint.paint_history(current_line_start_row, width, self.lines_for_display)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 38, in paint_history
    lines.append(fmtstr(line[:columns]))
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 549, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 140, in from_str
    tokens_and_strings = parse(s)
  File "/usr/local/lib/python2.7/site-packages/curtsies/escseqparse.py", line 32, in parse
    raise ValueError("Can't parse escape sequence: %r %r %r %r" % (s, repr(front), token, repr(rest)))
ValueError: Can't parse escape sequence: u'\x1b[31mTESTING\x1b(B\x1b[m' "u'TESTING\\x1b(B'" {'csi': u'\x1b[', 'seq': u'\x1b[m', 'intermed': u'', 'private': u'', 'command': u'm', 'numbers': []} "u''"
Keyan:~ Keyan$
````

Now when I try to start bpython again I get this strange error message:

````
Keyan:~ Keyan$ bpython
bpython version 0.14.1 on top of Python 2.7.9 /usr/local/opt/python/bin/python2.7

Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 163, in mainloop
    process_event(bpythonevents.RunStartupFileEvent())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 145, in process_event
    array, cursor_pos = repl.paint()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1134, in paint
    current_line = paint.paint_current_line(min_height, width, self.current_cursor_line)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1083, in current_cursor_line
    return (self.current_cursor_line_without_suggestion +
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1076, in current_cursor_line_without_suggestion
    ('' if self.coderunner.running else self.display_line_with_prompt))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1069, in display_line_with_prompt
    if self.done else
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 615, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 169, in from_str
    return FmtStr(Chunk(s))
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got '>>> '
Keyan:~ Keyan$
````

Could this be due to messing around with curtsies? Is the proper escape code ending sequence not being detected?

**Comment by thomasballinger** [comment]
The first one looks like messing with escape sequences in bpython (which it doesn't handle very well - this is a bug, bpython (really curtsies) should have a better escape sequence parser, at least good enough to deal with ordinary Blessings-style colored strings - and eventually maybe a whole terminal emulator) and the second one looks like using Curtsies >=0.2.0 with released bpython 0.14, which requires Curtsies <0.2.0.

**Comment by thomasballinger** [comment]
See https://github.com/thomasballinger/curtsies/issues/8 for the second one.

**Comment by keyan** [comment]
@thomasballinger Makes sense on the second count, I thought upgrading curtsies would resolve the first issue, only to produce a new one haha
