### ISSUE TITLE
F3 crashes on python3.4.3

### ISSUE THREAD

**Issue by gwk** [bpython/bpython#529]
i pip3 install from master, then run bpython and hit F3. tom said this was fixed in master a few days ago but it still crashes for me.

Annotated terminal session below; i added the "[F3]".

$ pip3 install --upgrade git+https://github.com/bpython/bpython.git@master
...
Successfully installed bpython-0.15.dev106
$ bpython3
bpython version 0.15.dev106 on top of Python 3.4.3 /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4
>>> [F3]
Traceback (most recent call last):
  File "/usr/local/bin/bpython3", line 9, in <module>
    load_entry_point('bpython==0.15.dev106', 'console_scripts', 'bpython')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/curtsies.py", line 81, in main
    interactive=(not exec_args))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/curtsies.py", line 182, in mainloop
    process_event(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/curtsies.py", line 140, in process_event
    repl.process_event(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 525, in process_event
    return self.process_key_event(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 659, in process_key_event
    greenlet.greenlet(self.edit_config).switch()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/repl.py", line 1031, in edit_config
    if self.open_in_external_editor(self.config.config_path):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bpython/repl.py", line 1004, in open_in_external_editor
    if subprocess.call(args) == 0:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**Comment by sebastinas** [comment]
This shouldn't crash anymore. So I'm closing this.

The error suggests that the editor that you've specified is not a valid executable or vi(m) is not available.

**Comment by gwk** [comment]
I am specifically trying to test the supposed fix; can you please tell me what I need to do to test the fix? I thought pip install from github master was the way to do it.

**Comment by gwk** [comment]
my EDITOR points to a sh script that consists of this line:
"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -w "$@"
(this is on OSX).

The -w flag specifies that sublime text should wait for the window to close before letting the cl process exit; this gives correct behavior for workflows like git rebase -i.

Given that this EDITOR works otherwise, I do think it is an issue with bpython. Would you like reopen this issue and retitle it, or should I open a new one?

**Comment by sebastinas** [comment]
Is that an sh script without shebang?

**Comment by gwk** [comment]
yes, it is... testing with one.

**Comment by gwk** [comment]
i get the same stack trace without a shebang, or with "#!/bin/sh".

**Comment by thomasballinger** [comment]
~~~
#!/usr/bin/env bash
"/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" -w "$@"
~~~
works for me - looking up things like the difference between "$@" and "%@"

**Comment by sebastinas** [comment]
Is the file also executable?

**Comment by gwk** [comment]
yes, file is executable.
$ ls -l /usr/local/gloss/bin/stw 
-rwxr-xr-x  1 root  wheel  295 Apr 29 17:36 /usr/local/gloss/bin/stw

here is a repro that does not depend on bpython:
$ python3
>>> import os, subprocess
>>> os.environ.get('EDITOR')
'/usr/local/gloss/bin/stw'
>>> subprocess.call([os.environ.get('EDITOR'), 'test.txt'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**Comment by gwk** [comment]
inserting '/bin/sh' at the head of the subprocess.call args works.

i have encountered this problem before; essentially python's subprocess does not know how to read shebang lines.

the fix for me is to change my EDITOR to be the command string:
`'"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -w "$@"'`

the fix for bpython appears to be to parse shebang lines yourself; not sure if it is worth it. i had some code that used to do this and it worked but probably comes at the cost of an extra open() and f.readline().

thanks for your help!

**Comment by sebastinas** [comment]
No, if `subprocess.call` is not able to execute a simple shell script that is executable and has correct shebang on your OS, `subprocess.call` needs to be fixed.
