### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#533]
I just updated bpython on my Mac laptop with `sudo pip install -U bpython`, but when I now try to start bpython I get this:
```
$ bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 7, in <module>
    from bpython.curtsies import main
  File "/Library/Python/2.7/site-packages/bpython/curtsies.py", line 14, in <module>
    from bpython.curtsiesfrontend.repl import Repl
  File "/Library/Python/2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 32, in <module>
    from bpython.config import (Struct, loadini, default_config_path,
  File "/Library/Python/2.7/site-packages/bpython/config.py", line 9, in <module>
    from six.moves.configparser import ConfigParser
ImportError: No module named configparser
```
Any idea how I could solve this?

**Comment by sebastinas** [comment]
Please see issue #494.
