### ISSUE TITLE
Interactive interpreter crashes when typing "Iterable"

### ISSUE THREAD

**Issue by jpalay** [bpython/bpython#534]
In the interactive interpreter, I try to type
```
>>> from collections import Iterable
>>> Iterable
```

Upon typing first character on the second line, bpython crashes. Here is the complete output:

```
>>> from collections import Iterable
>>> 
Traceback (most recent call last):
  File "/Users/josh/.virtualenvs/fake/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 488, in process_event
    return self.process_key_event(e)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_key_event
    self.add_normal_character(e)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/repl.py", line 599, in complete
    history=self.history)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/autocomplete.py", line 466, in get_completer_bpython
    return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/autocomplete.py", line 446, in get_completer
    cursor_offset, line, **kwargs)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/autocomplete.py", line 306, in matches
    matches.add(_callable_postfix(val, word))
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/autocomplete.py", line 536, in _callable_postfix
    if inspection.is_callable(value):
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/site-packages/bpython/inspection.py", line 279, in is_callable
    return isinstance(obj, collections.Callable)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/Users/josh/.virtualenvs/fake/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
TypeError: 'classmethod' object is not callable
```

Using bpython version 0.14.1 on top of Python 2.7.6

**Comment by sebastinas** [comment]
Could you please check if this is still an issue in master? fcd18378d7c67ef7f791dd4ecdb301174cc8dc2a should fix this.

**Comment by jpalay** [comment]
Yep, works fine on master. Thanks!
