### ISSUE TITLE
pkg_resources.DistributionNotFound: ndg-httpsclient under Python 2.6

### ISSUE THREAD

**Issue by centralniak** [bpython/bpython#542]
When I try to start **bpython==0.14.2** under **Python 2.6.9** it fails with:

```
Traceback (most recent call last):
  File "/home/piotr/.virtualenvs/comms-base/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/piotr/.virtualenvs/comms-base/lib/python2.6/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/home/piotr/.virtualenvs/comms-base/lib/python2.6/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/home/piotr/.virtualenvs/comms-base/lib/python2.6/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/piotr/.virtualenvs/comms-base/lib/python2.6/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ndg-httpsclient
```

bpython==0.14.1 works nice and so does 0.14.2 under Python 2.7.8 so I believe this is specific to Python 2.6 and bpython==0.14.2.

**Comment by sebastinas** [comment]
How did you install bpython without installing ndg-httpsclient? The package is listed as dependency for Python versions without proper SNI support (i.e. anything before 2.7.7). See also http://bpython-interpreter.org/known-issues-and-faq.html.

**Comment by centralniak** [comment]
```
piotr@piotr /tmp $ virtualenv bpython-26 -p `which python2.6`
Running virtualenv with interpreter /opt/python-2.6.9/bin/python2.6
New python executable in bpython-26/bin/python2.6
Also creating executable in bpython-26/bin/python
Installing setuptools, pip...done.
piotr@piotr /tmp $ . bpython-26/bin/activate
(bpython-26)piotr@piotr /tmp $ pip install bpython 
Downloading/unpacking bpython
[ ... ]
Successfully installed bpython pygments requests curtsies greenlet six blessings
Cleaning up...
(bpython-26)piotr@piotr /tmp $ bpython
Traceback (most recent call last):
  File "/tmp/bpython-26/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/bpython-26/lib/python2.6/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/tmp/bpython-26/lib/python2.6/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/tmp/bpython-26/lib/python2.6/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/bpython-26/lib/python2.6/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ndg-httpsclient
```

**Comment by centralniak** [comment]
Also my `$PYTHONPATH` is empty inside the virtualenv and six is at version 1.9.0

**Comment by sebastinas** [comment]
Which version of pip is that?

**Comment by sebastinas** [comment]
I've documented the issue in https://github.com/bpython/bsite/commit/fa16ce5f470201c336a5565a07463eb67d4a539a and upload a new version of the website later today. I don't think there is much we can do without breaking wheel support.

**Comment by centralniak** [comment]
Fair enough, pip (7.0.3) works fine but by default I've used 1.5.6. Cheers.
