### ISSUE TITLE
Crash with print("\033[6;3HHello")

### ISSUE THREAD

**Issue by goetzc** [bpython/bpython#545]
```python
bpython version 0.14.1 on top of Python 3.4.3 /usr/bin/python
>>> print("\033[6;3HHello")
                                       
Traceback (most recent call last):
  File "/usr/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.14.1', 'console_scripts', 'bpython')()
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 174, in mainloop
    process_event(e)
  File "/usr/lib/python3.4/site-packages/bpython/curtsies.py", line 145, in process_event
    array, cursor_pos = repl.paint()
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 1181, in paint
    history = paint.paint_history(current_line_start_row, width, self.lines_for_display)
  File "/usr/lib/python3.4/site-packages/bpython/curtsiesfrontend/replpainter.py", line 38, in paint_history
    lines.append(fmtstr(line[:columns]))
  File "/usr/lib/python3.4/site-packages/curtsies/formatstring.py", line 549, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/lib/python3.4/site-packages/curtsies/formatstring.py", line 140, in from_str
    tokens_and_strings = parse(s)
  File "/usr/lib/python3.4/site-packages/curtsies/escseqparse.py", line 25, in parse
    front, token, rest = peel_off_esc_code(rest)
  File "/usr/lib/python3.4/site-packages/curtsies/escseqparse.py", line 67, in peel_off_esc_code
    d['numbers'] = [int(x) for x in d['numbers'].split()]
  File "/usr/lib/python3.4/site-packages/curtsies/escseqparse.py", line 67, in <listcomp>
    d['numbers'] = [int(x) for x in d['numbers'].split()]
ValueError: invalid literal for int() with base 10: '6;3'
```

**Comment by sebastinas** [comment]
See https://github.com/thomasballinger/curtsies/issues/76.

**Comment by thomasballinger** [comment]
This most limited scope of this bug has been fixed in Curtsies master, but no release yet.

**Comment by thomasballinger** [comment]
There's been a Curtsies release now which the next release of bpython will use.
