### ISSUE TITLE
pkg_resources.DistributionNotFound: bpython==0.12

### ISSUE THREAD

**Issue by Nitesh-the-genius** [bpython/bpython#547]
I use linux mint and bpython won't work. It shows the following error:
Traceback (most recent call last):
  File "/usr/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: bpython==0.12

**Comment by sebastinas** [comment]
How did you install bpython?

**Comment by Nitesh-the-genius** [comment]
sudo apt-get install bpython

**Comment by sebastinas** [comment]
Them I'm afraid this is the wrong place. Please contact any of the Linux Mint support forums.

**Comment by Nitesh-the-genius** [comment]
Thanks for your help
