### ISSUE TITLE
pkg_resources.DistributionNotFound: ndg-httpsclient

### ISSUE THREAD

**Issue by kramer65** [bpython/bpython#556]
I've just upgrade bpython on my Ubuntu 14.04 server:
```
$ sudo pip install -U bpython
[sudo] password for kramer65:
Downloading/unpacking bpython from https://pypi.python.org/packages/source/b/bpython/bpython-0.14.2.tar.gz#md5=ce27e0b6092058e0233958c86a7df500
  Downloading bpython-0.14.2.tar.gz (184kB): 184kB downloaded
  Running setup.py (path:/tmp/pip_build_root/bpython/setup.py) egg_info for package bpython

    warning: no files found matching 'bpython/translations/*/LC_MESSAGES/bpython.mo'
Requirement already up-to-date: pygments in /usr/local/lib/python2.7/dist-packages (from bpython)
Downloading/unpacking requests from https://pypi.python.org/packages/2.7/r/requests/requests-2.7.0-py2.py3-none-any.whl#md5=564fb256f865a79f977e57b79d31659a (from bpython)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Requirement already up-to-date: curtsies>=0.1.18,<0.2.0 in /usr/local/lib/python2.7/dist-packages (from bpython)
Downloading/unpacking greenlet from https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.7.zip#md5=c2333a8ff30fa75c5d5ec0e67b461086 (from bpython)
  Downloading greenlet-0.4.7.zip (77kB): 77kB downloaded
  Running setup.py (path:/tmp/pip_build_root/greenlet/setup.py) egg_info for package greenlet

Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from bpython)
Installing collected packages: bpython, requests, greenlet
  Found existing installation: bpython 0.14.1
    Uninstalling bpython:
      Successfully uninstalled bpython
  Running setup.py install for bpython

    warning: no files found matching 'bpython/translations/*/LC_MESSAGES/bpython.mo'
    Installing bpython-urwid script to /usr/local/bin
    Installing bpython-curses script to /usr/local/bin
    Installing bpdb script to /usr/local/bin
    Installing bpython script to /usr/local/bin
  Found existing installation: requests 2.6.0
    Uninstalling requests:
      Successfully uninstalled requests
  Found existing installation: greenlet 0.4.5
    Uninstalling greenlet:
      Successfully uninstalled greenlet
  Running setup.py install for greenlet
    building 'greenlet' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/greenlet.o -o build/lib.linux-x86_64-2.7/greenlet.so

Successfully installed bpython requests greenlet
Cleaning up...
$
```
But when I now start bpython I get the following error:
```
$ bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2951, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 561, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 870, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 755, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ndg-httpsclient
```
Any idea what could be wrong?

**Comment by kramer65** [comment]
I just solved it by doing a simple `sudo pip install ndg_httpsclient`.

Maybe this should be added to the setup.py?

**Comment by sebastinas** [comment]
Does any one of the points mentioned in http://bpython-interpreter.org/known-issues-and-faq.html apply to you?

**Comment by kramer65** [comment]
Not as far as I know. Pip is the most recent version and I use python version 0.14.2 on top of Python 2.7.6 /usr/bin/python (on Ubuntu 14.04). But things work again now.. :-)

**Comment by jeffeb3** [comment]
I'm also getting this issue, and it's because ndg_httpsclient was not installed correctly, but I don't want to fight it, so I just used apt-get install bpython and the repo version works fine. BTW, I'm also using ubuntu 14.04.
