### ISSUE TITLE
Undo triggers exception when running with -i flag

### ISSUE THREAD

**Issue by ohnoleo** [bpython/bpython#563]
If bpython is run using -i, undo fails with this exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.15.dev167', 'console_scripts', 'bpython')()
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsies.py", line 88, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsies.py", line 186, in mainloop
    process_event(e)
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsies.py", line 147, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 524, in process_event
    return self.process_key_event(e)
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 648, in process_key_event
    self.prompt_undo()
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 1451, in prompt_undo
    greenlet.greenlet(prompt_for_undo).switch()
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 1447, in prompt_for_undo
    n = BpythonRepl.prompt_undo(self)
  File "/usr/local/lib/python2.7/dist-packages/bpython/repl.py", line 815, in prompt_undo
    self.interp.timer.estimate() < self.config.single_undo_time):
AttributeError: InteractiveInterpreter instance has no attribute 'timer'
```

Looks like the command line flag causes the InteractiveInterpreter base class to get constructed instead of the Interpreter class in bpython/repl.py, so no timer gets created.

**Comment by thomasballinger** [comment]
This should be (relatively) straightforward to fix if someone else wants to take a shot at it. As @ohnoleo says, the wrong interpreter is being constructed when bpython is run with `-i`.

**Comment by mgracer48** [comment]
I can take a shot at this

**Comment by thomasballinger** [comment]
@mgracer48 Great! Let me know if you've got questions, you can post them here or email me.

**Comment by thomasballinger** [comment]
@mgracer48 Any update on this? As far as I can tell, in the file bpython/curtsies.py the `Interp` class should be imported from `bpython.curtsiesfrontend.interpreter` and used instead of the code.InteractiveInterpreter class in the `main()` method.

**Comment by thomasballinger** [comment]
@mgracer48 Because we're doing a release soon, I'm going to handle this for now. Let me know if you'd like to contribute with something else in the future.

**Comment by thomasballinger** [comment]
fixed by https://github.com/bpython/bpython/commit/455932864ab25b7422b04af94930f434c17700e5
