### ISSUE TITLE
Python 3.5 and _curses

### ISSUE THREAD

**Issue by batisteo** [bpython/bpython#564]
```python
$ bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.14.2', 'console_scripts', 'bpython')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/bpython/curtsies.py", line 9, in <module>
    import curtsies
  File "/usr/local/lib/python3.5/site-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "/usr/local/lib/python3.5/site-packages/curtsies/window.py", line 30, in <module>
    import blessings
  File "/usr/local/lib/python3.5/site-packages/blessings/__init__.py", line 5, in <module>
    import curses
  File "/usr/local/lib/python3.5/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
```
Is bpython not yet compatible with 3.5 or it's just a PYTHON_PATH issue?

**Comment by sebastinas** [comment]
This looks like an issue in your Python build. Why don't you have _curses?

**Comment by thomasballinger** [comment]
I'd like to close if there's no additional information about it - @batisteo, did you figure out what the problem was?

**Comment by batisteo** [comment]
Not really, it must be my installation.
Let's close it.

**Comment by Kasablanka1996** [comment]
i got the same error,how did you solve it?

**Comment by Kasablanka1996** [comment]
@batisteo

**Comment by batisteo** [comment]
By not using it. I wanted to use it on a compiled version without venv. This was related to my clunky install of py3.5, sorry I can't help. Open a new ticket if needed.

**Comment by JesseWatson63** [comment]
curses does not exist for windows (not really at least).  There is a way around it, but I can not figure it out nor are these devs updating with instructions on how to do it.  But according to pypi it can be installed.  BOOOOOO these devs, Booooooooo

**Comment by vlcinsky** [comment]
The same happens with python 3.6 on Ubuntu 16.04

**Comment by vlcinsky** [comment]
@sebastinas 
Good.
I run python 3.6.1 installed by `pyenv`.

Following advice at https://github.com/pyenv/pyenv/issues/240 I installed libraries for curses:

    sudo apt-get install libncurses5 libncurses5-dev libncursesw5

Then uninstalled given pyenv for 3.6.1 and installed again.

Finally it works.

Thanks for pointing to the root of the problem (python being installed without support for curses).
