### ISSUE TITLE
bpython gets stuck on cygwin

### ISSUE THREAD

**Issue by ayush--s** [bpython/bpython#570]
I've installed bpython on cygwin64's python 3.4.2 using pip. while the installation succeeded, the bpython gets stuck as shown in the screenshot

![img](http://i.imgur.com/Dbtu6Dvl.jpg)

**Comment by cool-RR** [comment]
I've also experienced it. bpython 0.16, Python 2.7.5, CentOS 7.1.1503.

**Comment by ayush--s** [comment]
@cool-RR can you provide some debug logs (maybe strace). I no longer use windows so can't :disappointed:

**Comment by cool-RR** [comment]
@ayush--s  This is not Windows, it's Centos. Show me exactly how to produce the logs and I will.

**Comment by ata2001** [comment]
You can turn on logging with the `-L` switch. The log will be saved as bpython.log in your current directory.

`bpython -L`

**Comment by cool-RR** [comment]
Thanks Attila. I did that now and there was absolutely nothing in the log, it was completely empty. All I can show you is the traceback that appeared after I pressed Ctrl-C. I'm not sure if it helps:

```
[root@lala ~]# bpython -L                                                     
bpython version 0.16 on top of Python 2.6.6 /usr/bin/python                              
Traceback (most recent call last):                                                       
  File "/usr/bin/bpython", line 11, in <module>                                          
    sys.exit(main())                                                                     
  File "/usr/lib/python2.6/site-packages/bpython/curtsies.py", line 187, in main         
    with repl.window as win:                                                             
  File "/usr/lib/python2.6/site-packages/curtsies/window.py", line 255, in __enter__     
    self.top_usable_row, _ = self.get_cursor_position()                                  
  File "/usr/lib/python2.6/site-packages/curtsies/window.py", line 298, in get_cursor_pos
ition                                                                                    
    c = retrying_read()                                                                  
  File "/usr/lib/python2.6/site-packages/curtsies/window.py", line 292, in retrying_read 
    'cursor get pos response read interrupted'                                           
ValueError: cursor get pos response read interrupted                                     
```

**Comment by ata2001** [comment]
@cool-RR What terminal emulator are you using?

**Comment by cool-RR** [comment]
I'm not sure whether this is the right answer, but I use ConEmu on Windows,
and I do SSH into the CentOS machine.

Note that when I use PuDB and use the shell from there, which uses bpython,
it does work. I only get this issue when using bpython directly.

**Comment by ata2001** [comment]
@cool-RR I think it's a windows specific problem. I don't have windows, so I can't reproduce it.

Did you try running any other curtsies based software in that same terminal emulator.

**Comment by cool-RR** [comment]
Hmm, I don't really use any other curtsies-based programs, I don't know
what they are. I can try something if it's easy to install.

I've now tried to SSH to the server using Putty rather than ConEmu/MSYS and
it worked. Maybe it's an issue with ConEmu/MSYS or with my configuration.

**Comment by ata2001** [comment]
@cool-RR You could try this: https://raw.githubusercontent.com/thomasballinger/curtsies/master/examples/tictactoeexample.py

**Comment by thomasballinger** [comment]
@cool-RR also not that when you're running bpython directly you're running it under Python 2.6, which we not longer officially support - I haven't tried bpython on 2.6 for a while, and while I don't recognized this failure it could be related to that.
