### ISSUE TITLE
Crash with print('\x1b[31mhello\x1b(B\x1b[m')

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#619]
Here's the crash and stacktrace:

```
$ bpython3
bpython version 0.15 on top of Python 3.5.1+ /usr/bin/python3
>>> print('\x1b[31mhello\x1b(B\x1b[m')
hello
Traceback (most recent call last):
  File "/usr/bin/bpython3", line 9, in <module>
    load_entry_point('bpython==0.15', 'console_scripts', 'bpython')()
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/lib/python3/dist-packages/bpython/curtsiesfrontend/repl.py", line 1356, in paint
    self.lines_for_display)
  File "/usr/lib/python3/dist-packages/bpython/curtsiesfrontend/replpainter.py", line 39, in paint_history
    lines.append(fmtstr(line[:columns]))
  File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 617, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 156, in from_str
    tokens_and_strings = parse(s)
  File "/usr/lib/python3/dist-packages/curtsies/escseqparse.py", line 27, in parse
    front, token, rest = peel_off_esc_code(rest)
  File "/usr/lib/python3/dist-packages/curtsies/escseqparse.py", line 79, in peel_off_esc_code
    d['numbers'] = [int(x) for x in d['numbers'].split(';')]
  File "/usr/lib/python3/dist-packages/curtsies/escseqparse.py", line 79, in <listcomp>
    d['numbers'] = [int(x) for x in d['numbers'].split(';')]
ValueError: invalid literal for int() with base 10: ''
```

Here's how I ended up with the sequence:

```
from blessings import Terminal
t = Terminal()
t.red('hello')
print(t.red('hello'))  # Crashes bpython
```

Please note that #545 does *not* crash (so #545 is correctly closed).  However, I guess that the underlying bug is similar.

**Comment by thomasballinger** [comment]
Related to https://github.com/bpython/bpython/issues/340, it would be nice to parse these properly or at least not crash.

**Comment by BenWiederhake** [comment]
Oh, sorry, looks like I haven't searched thoroughly enough.  Closing as duplicate.
