### ISSUE TITLE
"Show source" on empty line throws exception

### ISSUE THREAD

**Issue by Trundle** [bpython/bpython#642]
```
bpython version 0.16 on top of Python 2.7.12+ /tmp/_env/bin/python2
>>> 
Traceback (most recent call last):
  File "/tmp/_env/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/tmp/_env/local/lib/python2.7/site-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/tmp/_env/local/lib/python2.7/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/tmp/_env/local/lib/python2.7/site-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/tmp/_env/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1468, in paint
    1, width, self.status_bar.current_line, self.config)
  File "/tmp/_env/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 227, in paint_statusbar
    return fsarray([func(msg.ljust(columns))[:columns]])
  File "/tmp/_env/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 628, in fmtstr
    string = FmtStr.from_str(string)
  File "/tmp/_env/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 180, in from_str
    return FmtStr(Chunk(s))
  File "/tmp/_env/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got 'Nothing to get source of
                                          '
```

Seems like a Python 2 issue only, not reproducible under Python 3.

**Comment by Trundle** [comment]
This was introduced by 325d3bbdee1d9d8394cbd0e166e85969eeb4d194.
