### ISSUE TITLE
DependencyWarning with Pacman

### ISSUE THREAD

**Issue by polypmer** [bpython/bpython#647]
Hi, my bpython stopped working outside of virtualenv. I'm running Arch Linux (pacman package manager). Also, I've tried installing requests with pacman, but there is still some funny business going on.

     Traceback (most recent call last):
      File "/usr/bin/bpython", line 11, in <module>
        load_entry_point('bpython==0.16', 'console_scripts', 'bpython')()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
        return ep.load()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2264, in load
        return self.resolve()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2270, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python3.5/site-packages/bpython/curtsies.py", line 14, in <module>
        from bpython.curtsiesfrontend.repl import BaseRepl
      File "/usr/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 30, in <module>
        from bpython.repl import Repl as BpythonRepl, SourceNotFound
      File "/usr/lib/python3.5/site-packages/bpython/repl.py", line 52, in <module>
        from bpython.paste import PasteHelper, PastePinnwand, PasteFailed
      File "/usr/lib/python3.5/site-packages/bpython/paste.py", line 29, in <module>
        import requests
      File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
        from .packages.urllib3.exceptions import DependencyWarning
    ImportError: cannot import name 'DependencyWarning'

**Comment by sebastinas** [comment]
This looks like an issue in the requests package provided by Arch. I'd recommend to report this issue in Arch's bug tracking system.
