### ISSUE TITLE
When using parsley exceptions kill bpython

### ISSUE THREAD

**Issue by jkbbwr** [bpython/bpython#651]
The following traceback is thrown

```
Traceback (most recent call last):
  File "/home/jakob/.virtualenvs/copper/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsies.py", line 89, in process_event_and_paint
    self.process_event(e)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 584, in process_event
    return self.process_key_event(e)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 711, in process_key_event
    self.on_enter()
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 794, in on_enter
    self.push(self.current_line, insert_into_history=insert_into_history)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 1058, in push
    self.run_code_and_maybe_finish()
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/repl.py", line 1061, in run_code_and_maybe_finish
    r = self.coderunner.run_code(for_code=for_code)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/coderunner.py", line 136, in run_code
    request = self.code_greenlet.switch()
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/curtsiesfrontend/coderunner.py", line 178, in _blocking_run_code
    unfinished = self.interp.runsource(self.source)
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/repl.py", line 160, in runsource
    filename, symbol)
  File "/usr/lib64/python3.5/code.py", line 75, in runsource
    self.runcode(code)
  File "/usr/lib64/python3.5/code.py", line 95, in runcode
    self.showtraceback()
  File "/home/jakob/.virtualenvs/copper/lib/python3.5/site-packages/bpython/repl.py", line 215, in showtraceback
    l[len(l):] = traceback.format_exception_only(t, v)
  File "/usr/lib64/python3.5/traceback.py", line 136, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "/usr/lib64/python3.5/traceback.py", line 439, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'ParseError'
```

When an exception in parsely is thrown

Smallest reproducable example is 

```
import parsley

grammar = """
name = <letter letterOrDigit*>
"""

parser = parsley.makeGrammar(grammar, {})
parser("3").name()
```

**Comment by Trundle** [comment]
Thank you for the bug report and a way to reproduce the bug!

Unfortunately, it seems that this issue is rather a bug (or at least some unexpected behaviour) in the standard library of Python itself rather than in bpython. What happens here is that when Python prints an exception, it also prints the exception that caused the exception (if there is a causing exception). To avoid endless loops, the printing code keeps track of which exceptions it has already seen in a set. Unfortunately, there is a difference in the code that the CPython interpreter uses and the code used by bpython. The interpreter-internal code ignores every exception that occurs while adding the exception to the bookkeeping-set (see https://hg.python.org/cpython/file/8ee4ed577c03/Python/pythonrun.c#l814 ff). bpython uses the traceback module and that doesn't catch exceptions when adding the exception to the set (see https://hg.python.org/cpython/file/8ee4ed577c03/Lib/traceback.py#l462).

I think it makes sense to open an issue for that on the CPython bugtracker. If nobody beats me to it, I will do so tomorrow. I can't think of a quick fix in bpython right now (except copying half of the traceback module).

**Comment by jkbbwr** [comment]
Thanks for the fast reply! Let me know if you need any help. I have switched to bpython over ipython and want to help make it even stronger.

**Comment by Trundle** [comment]
I reported the issue to CPython (http://bugs.python.org/issue28603).

I also wrote some hackish "fix" for the issue (https://gist.github.com/Trundle/850fa6efbe7c1ef1db1ce5269a8e7d22). I will sleep on it and then decide whether it's worthwhile to submit it as pull request.
