### ISSUE TITLE
crash when attempting to use an unsupported SGR code

### ISSUE THREAD

**Issue by mic-e** [bpython/bpython#657]
mic@mic ~ $ bpython3
    bpython version 0.16 on top of Python 3.5.2+ /usr/bin/python3
    >>> print("\x1b[2ma")
    a
    Traceback (most recent call last):
      File "/usr/bin/bpython3", line 11, in <module>
        load_entry_point('bpython==0.16', 'console_scripts', 'bpython')()
      File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 190, in main
        exit_value = repl.mainloop()
      File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 125, in mainloop
        self.process_event_and_paint(e)
      File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 100, in process_event_and_paint
        scrolled = self.window.render_to_terminal(array, cursor_pos)
      File "/usr/lib/python3/dist-packages/curtsies/window.py", line 409, in render_to_terminal
        if line == self._last_lines_by_row.get(row, None):
      File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 367, in __eq__
        return str(self) == str(other)
      File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 328, in __unicode__
        self._unicode = ''.join(unicode(fs) for fs in self.basefmtstrs)
      File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 328, in <genexpr>
        self._unicode = ''.join(unicode(fs) for fs in self.basefmtstrs)
      File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 106, in __unicode__
        value = self.color_str
      File "/usr/lib/python3/dist-packages/curtsies/formatstring.py", line 96, in color_str
        assert k in xforms, "XXX Do we actually get cases like this?"
    AssertionError: XXX Do we actually get cases like this?

**Comment by thomasballinger** [comment]
I guess the answer to the assertion error question is "Yes, we do." We should be stripping out escape sequences that we don't recognize (or that don't end in clears, like this one).

**Comment by thomasballinger** [comment]
If anyone's looking at fixing this: making the change to Curtsies is doable and fairly beginner friendly, I'm happy to talk about how to go about this, email me or find me in `#bpython` on freenode.

**Comment by ata2001** [comment]
Created PR: https://github.com/thomasballinger/curtsies/pull/100

**Comment by thomasballinger** [comment]
Fixed by @ata2001, no longer crashes.

**Comment by thomasballinger** [comment]
Well this will be fixed once we do a new release of Curtsies.

**Comment by thomasballinger** [comment]
We did a new release of Curtsies!
