### ISSUE TITLE
Fails to take keyboard input after if or loop statement  

### ISSUE THREAD

**Issue by Mofiqul** [bpython/bpython#668]
Hello sir, I have a problem to type my next code after any conditional statement or loop
this here the error:

```
>>> a = 5; b = 5
>>> if (a is b):
...     print()
Traceback (most recent call last):
  File "/usr/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.15', 'console_scripts', 'bpython')()
  File "/usr/lib/python2.7/dist-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/usr/lib/python2.7/dist-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/usr/lib/python2.7/dist-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 1428, in paint
    if self.matches_iter.completer else None)
  File "/usr/lib/python2.7/dist-packages/bpython/curtsiesfrontend/replpainter.py", line 182, in paint_infobox
    if matches else [])
  File "/usr/lib/python2.7/dist-packages/bpython/curtsiesfrontend/replpainter.py", line 78, in matches_lines
    for i in range(0, len(matches), words_wide)]
  File "/usr/lib/python2.7/dist-packages/curtsies/formatstring.py", line 253, in join
    for i, s in enumerate(iterable):
  File "/usr/lib/python2.7/dist-packages/bpython/curtsiesfrontend/replpainter.py", line 77, in <genexpr>
    for m in matches[i:i+words_wide])
  File "/usr/lib/python2.7/dist-packages/curtsies/formatstring.py", line 617, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/lib/python2.7/dist-packages/curtsies/formatstring.py", line 169, in from_str
    return FmtStr(Chunk(s))
  File "/usr/lib/python2.7/dist-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got 'pass    '
```

**Comment by thomasballinger** [comment]
Could you paste the output you get for:

```
tomb@tom-mba ~$ bpython
bpython version 0.17.dev11 on top of Python 2.7.11rc1 /Users/tomb/.pyenv/versions/2.7.11rc1/bin/python2.7
>>> import curtsies; curtsies.__version__
'0.2.7'
>>>
```

**Comment by thomasballinger** [comment]
Although a good bet is that upgrading bpython will fix this - you might try that first.

**Comment by Mofiqul** [comment]
Yap upgrading solve that issue. Happy to use bpython  :)

**Comment by sebastinas** [comment]
Thanks for checking. Closing.

**Comment by nuzz** [comment]
I'm not sure if this violates github issue etiquette (commenting on a closed issue) but I have the same exact error and I'm all up to date on bpython (and cutsies) for that matter.

`bpython version 0.16 on top of Python 2.7.13 /usr/local/opt/python/bin/python2.7
>>> l = ['1','two','333']
>>> for item in l:
...
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1447, in paint
    if self.matches_iter.completer else None)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 182, in paint_infobox
    if matches else [])
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 78, in matches_lines
    for i in range(0, len(matches), words_wide)]
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 264, in join
    for i, s in enumerate(iterable):
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 77, in <genexpr>
    for m in matches[i:i+words_wide])
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 628, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 180, in from_str
    return FmtStr(Chunk(s))
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got 'pass    '`

**Comment by thomasballinger** [comment]
Would you report what you get from
```
tomb@tom-mba ~$ bpython
bpython version 0.17.dev11 on top of Python 2.7.11rc1 /Users/tomb/.pyenv/versions/2.7.11rc1/bin/python2.7
>>> import curtsies; curtsies.__version__
'0.2.7'
>>>
```

**Comment by nuzz** [comment]
```python
➜  ~ bpython
bpython version 0.16 on top of Python 2.7.13 /usr/local/opt/python/bin/python2.7
>>> import curtsies; curtsies.__version__
'0.2.11'```

**Comment by nuzz** [comment]
After digging into this issue for a long time, I tried installing on a new mac dev machine and it works fine. There must be something screwy with my old dev env.

**Comment by thomasballinger** [comment]
Thanks for the update @nuzz
