### ISSUE TITLE
bpython-urwid crash on "json.dumps" completion

### ISSUE THREAD

**Issue by glyph** [bpython/bpython#672]
```console
$ mktmpenv --python="$(which python3.6)"
Running virtualenv with interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/python3.6
Also creating executable in /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-b2365fef2bc35da) $ pip install bpython[urwid]
Collecting bpython[urwid]
  Downloading http://127.0.0.1:3141/root/pypi/+f/2f6/62b1969353704/bpython-0.16-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 78.3MB/s 
Collecting requests (from bpython[urwid])
  Downloading http://127.0.0.1:3141/root/pypi/+f/5e4/32dcf5bd1e340/requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 107.7MB/s 
Requirement already satisfied: six>=1.5 in ./lib/python3.6/site-packages (from bpython[urwid])
Collecting greenlet (from bpython[urwid])
Collecting pygments (from bpython[urwid])
  Downloading http://127.0.0.1:3141/root/pypi/+f/ce6/7fc58b51ffd29/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 93.3MB/s 
Collecting curtsies>=0.1.18 (from bpython[urwid])
  Downloading http://127.0.0.1:3141/root/pypi/+f/562/3081d32e348cf/curtsies-0.2.11-py2.py3-none-any.whl
Collecting urwid; extra == "urwid" (from bpython[urwid])
Collecting wcwidth>=0.1.4 (from curtsies>=0.1.18->bpython[urwid])
  Downloading http://127.0.0.1:3141/root/pypi/+f/9fb/9f073e3560424/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting blessings>=1.5 (from curtsies>=0.1.18->bpython[urwid])
Installing collected packages: requests, greenlet, pygments, wcwidth, blessings, curtsies, urwid, bpython
Successfully installed blessings-1.6 bpython-0.16 curtsies-0.2.11 greenlet-0.4.12 pygments-2.2.0 requests-2.13.0 urwid-1.3.1 wcwidth-0.1.7
(tmp-b2365fef2bc35da) $ bpython-urwid 
```

Here, I type:

```python
>>> import json
>>> json.dumps(
```

And as soon as I type the opening parenthesis, I get this exception, and `bpython-urwid` exits:

```
Traceback (most recent call last):
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/bin/bpython-urwid", line 11, in <module>
    sys.exit(main())
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/bpython/urwid.py", line 1317, in main
    myrepl.main_loop.screen.run_wrapper(run_with_screen_before_mainloop)
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/display_common.py", line 763, in run_wrapper
    return fn()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/bpython/urwid.py", line 1268, in run_with_screen_before_mainloop
    myrepl.main_loop.run()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/bpython/urwid.py", line 1016, in <lambda>
    0, lambda *args: self._populate_completion())
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/bpython/urwid.py", line 821, in _populate_completion
    widget_list.append(urwid.Text(markup))
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/widget.py", line 836, in __init__
    self.set_text(markup)
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/widget.py", line 879, in set_text
    self._text, self._attrib = decompose_tagmarkup(markup)
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/util.py", line 375, in decompose_tagmarkup
    tl, al = _tagmarkup_recurse(tm, None)
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/util.py", line 395, in _tagmarkup_recurse
    tl, al = _tagmarkup_recurse( element, attr )
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/util.py", line 413, in _tagmarkup_recurse
    return _tagmarkup_recurse( element, attr )
  File "/Users/glyph/.virtualenvs/tmp-b2365fef2bc35da/lib/python3.6/site-packages/urwid/util.py", line 416, in _tagmarkup_recurse
    raise TagMarkupException("Invalid markup element: %r" % tm)
urwid.util.TagMarkupException: Invalid markup element: False
(tmp-b2365fef2bc35da) $ 
```

This doesn't happen with vanilla bpython.

**Comment by thomasballinger** [comment]
Thanks for reporting. I can repro in 3.6 but not 3.5, will look into it.

**Comment by thomasballinger** [comment]
It appears the problem is in parseing the `*` in the new signature for loads in 3.5:
`json.loads(s, *, encoding=None, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw)`

Unfortunately the completion code for bpython-urwid and bpython diverged some time ago. I'll look at a one off fix for urwid.

**Comment by thomasballinger** [comment]
Actually it's default values for keyword-only arguments.

**Comment by glyph** [comment]
Thanks for the quick follow-up!  Looking forward to the next release.
