### ISSUE TITLE
Alt+arrow keys should jump a word at a time

### ISSUE THREAD

**Issue by maxnordlund** [bpython/bpython#689]
This is consistent with most *nix system AFIK. At least vim, fish and bash do this. The common escape code is \escf and \escb for forward and backword respectively.

**Comment by thomasballinger** [comment]
How are you invoking bpython? This should work in normal bpython already, it might be a key character sequence issue. Or if you're using bpython-curses or bpython-urwid, then I agree :)

**Comment by maxnordlund** [comment]
Just like `bpython` in a terminal, or how do you mean?

**Comment by thomasballinger** [comment]
Yep, but if this is what you're doing already try

python -m curtsies.events

to see what the key sequence is.

Do these keys work for you in bash with this terminal/keyboard/os?

**Comment by maxnordlund** [comment]
```
/Users/maxno/.pyenv/versions/3.6.0/lib/python3.6/runpy.py:125: RuntimeWarning: 'curtsies.events' found in sys.modules after import of package 'curtsies', but prior to execution of 'curtsies.events'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
press a bunch of keys (not at the same time, but you can hit them pretty quickly)
---
b'\x1bf'
<Esc+f>
---
b'\x1bb'
<Esc+b>
Traceback (most recent call last):
  File "/Users/maxno/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/maxno/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/maxno/.pyenv/versions/venvs/1f4bcc50-6589-11e7-bd6c-f3c5e4c7a6b2/lib/python3.6/site-packages/curtsies/events.py", line 312, in <module>
    try_keys()
  File "/Users/maxno/.pyenv/versions/venvs/1f4bcc50-6589-11e7-bd6c-f3c5e4c7a6b2/lib/python3.6/site-packages/curtsies/events.py", line 298, in try_keys
    chars = os.read(sys.stdin.fileno(), 1000)
KeyboardInterrupt
```

Bash does not work in iTerm/Mac Swedish Pro/Mac OS X 10.12.5 (16F73)

**Comment by thomasballinger** [comment]
These are your arrow keys? As you say, they produce \escf/\escb, which I'd expect to work. I don't know what the problem might be here. What's the curtsies version you're using? (import curtsies; curtsies.__version__)

**Comment by maxnordlund** [comment]
Yes they are, when I try to get the version I just get an error:

```
>>> import curtsies; curtsies.version
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import curtsies; curtsies.version
AttributeError: module 'curtsies' has no attribute 'version'
```

**Comment by thomasballinger** [comment]
Formatting messed up, I meant `__ version__`

**Comment by maxnordlund** [comment]
0.2.11

**Comment by logileifs** [comment]
Also doesn't work for me on Ubuntu 14.04. My normal system 'word jump keys' are Ctrl+Left/Right however and neither ctrl or alt + arrow keys work for me in bpython

**Comment by thomasballinger** [comment]
Curious if either of you have learned anything about this, if you still have it, and which bpython versions you're running.

**Comment by maxnordlund** [comment]
From what I've gathered after redoing my iTerm config amongst other things is that bpython correctly accepts meta+arrow keys, and jumps between words accordingly.

But it only considers whitespace as a word separator, unlike fish, bash and vanilla python that looks at non-ascii (and unicode equivalents) characters.

```python
bpython version 0.17.1 on top of Python 3.6.4 /usr/local/opt/python3/bin/python3.6
>>> # The expected jump points for:
>>> foo.bar.baz + 1
>>> # should be:
>>> <>foo<>.<>bar<>.<>baz<> <>+<> <>1<>
>>> # but is instead:
>>> <>foo.bar.baz<> <>+<> <>1<>
```

Does that make more sense?

**Comment by maxnordlund** [comment]
Please go ahead if you already know what's needed 👍

**Comment by raphtown** [comment]
Having this issue on bpython 0.17.1 with CentOS 7.6 . Wondering if this ever got addressed?
