### ISSUE TITLE
using bpdb in a bpython interpreter doesn't work

### ISSUE THREAD

**Issue by toejough** [bpython/bpython#698]
I don't seem to be able to use bpdb if I'm also working in the bpython interpreter.

The direct problem is that I get `TypeError: argument must be an int, or have a fileno() method.`

I can reproduce by triggering a `bpdb.set_trace()` debugging call from within bpython:

**bpdb_test.py**
```python
import bpdb
bpdb.set_trace()
```

**importing in bpython**
```shell
> bpython
bpython version 0.16 on top of Python 3.5.2 /<venv>/bin/python
>>> import bpdb_test
--Return--
> /<pwd>/bpdb_test.py(2)<module>()->None
-> bpdb.set_trace()
Use "B" to enter bpython, Ctrl-d to exit it.
(BPdb) B
bpython version 0.16 on top of Python 3.5.2 /<venv>/bin/python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import bpdb_test
  File "/<pwd>/bpdb_test.py", line 2, in <module>
    bpdb.set_trace()
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/bdb.py", line 93, in dispatch_return
    self.user_return(frame, arg)
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/pdb.py", line 291, in user_return
    self.interaction(frame, None)
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/pdb.py", line 346, in interaction
    self._cmdloop()
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/pdb.py", line 412, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/<home>/.pyenv/versions/3.5.2/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/<venv>/lib/python3.5/site-packages/bpdb/debugger.py", line 46, in do_Bpython
    bpython.embed(self.curframe.f_locals, ['-i'])
  File "/<venv>/lib/python3.5/site-packages/bpython/__init__.py", line 36, in embed
    return main(args, locals_, banner)
  File "/<venv>/lib/python3.5/site-packages/bpython/curtsies.py", line 187, in main
    with repl.window as win:
  File "/<venv>/lib/python3.5/site-packages/curtsies/window.py", line 254, in __enter__
    self.cbreak.__enter__()
  File "/<venv>/lib/python3.5/site-packages/curtsies/termhelpers.py", line 20, in __enter__
    self.original_stty = termios.tcgetattr(self.stream)
TypeError: argument must be an int, or have a fileno() method.
>>>
```

Running bpdb works fine outside of bpython:
```shell
python bpdb_test.py
--Return--
> /<pwd>/bpdb_test.py(2)<module>()->None
-> bpdb.set_trace()
Use "B" to enter bpython, Ctrl-d to exit it.
(BPdb) B
bpython version 0.16 on top of Python 3.5.2 /<venv>/bin/python
>>>
```

**Comment by ayush--s** [comment]
bump. this problem also appears while using fabric library from bpython

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    p.run()
  File "/src/models.py", line 132, in run
    self.setup_instance()
  File "/src/models.py", line 171, in setup_instance
    execute(self.setup_commands, obj=self, hosts=[self.server_public_ip])
  File "/opt/venv/lib/python3.6/site-packages/fabric/tasks.py", line 385, in execute
    multiprocessing
  File "/opt/venv/lib/python3.6/site-packages/fabric/tasks.py", line 275, in _execute
    return task.run(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/src/models.py", line 162, in setup_commands
    run('cp -r ~/src ~/pipeline_src')
  File "/opt/venv/lib/python3.6/site-packages/fabric/network.py", line 682, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/fabric/operations.py", line 1091, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/opt/venv/lib/python3.6/site-packages/fabric/operations.py", line 934, in _run_command
    capture_buffer_size=capture_buffer_size)
  File "/opt/venv/lib/python3.6/site-packages/fabric/operations.py", line 757, in _execute
    with char_buffered(sys.stdin):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/venv/lib/python3.6/site-packages/fabric/context_managers.py", line 433, in char_buffered
    old_settings = termios.tcgetattr(pipe)
TypeError: argument must be an int, or have a fileno() method.
```
