### ISSUE TITLE
bpython crashes while typing indented code blocks

### ISSUE THREAD

**Issue by jmkinder1** [bpython/bpython#699]
When I type a statement that requires an indented code block (if, def, for, while, etc.), bpython crashes when I type the first character inside the block.

In the following example, I am running bpython.  I typed "if True:", hit enter, then attempted to type "print" on the next line.  It appears that the `ValueError` exception was raised as bpython attempted to suggest the "pass  ' statement as an autocompletion immediately after I pressed the `p` key.  bpython exited and printed the following to my terminal:

```
>>> if True:
...     
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 99, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1428, in paint
    if self.matches_iter.completer else None)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 182, in paint_infobox
    if matches else [])
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 78, in matches_lines
    for i in range(0, len(matches), words_wide)]
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 264, in join
    for i, s in enumerate(iterable):
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 77, in <genexpr>
    for m in matches[i:i+words_wide])
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 628, in fmtstr
    string = FmtStr.from_str(string)
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 180, in from_str
    return FmtStr(Chunk(s))
  File "/usr/local/lib/python2.7/site-packages/curtsies/formatstring.py", line 70, in __init__
    raise ValueError("unicode string required, got %r" % string)
ValueError: unicode string required, got 'pass    '
```

This occurred for multiple indented code block I tried to write.  (For example, typing `x` gave the same errors, only with `'xrange'` in place of `'pass   '`.)

I installed (and recently updated) Python (version 2.7.13) with Homebrew.  I used pip (version 9.0.1) to install bpython.  The same problem occurs in versions 0.15 and 0.16 of bpython on my machine, but not in version 0.14.  (All three versions were installed via the same version of pip from Homebrew.)  I am running Mac OS X Yosemite.

I solved my problem by rolling back to version 0.14 of bpython.  However, I would consider this an issue with current verisons of bpython, or at least with the dependencies used by pip.

**Comment by jmkinder1** [comment]
My apologies.  I am no longer able to reproduce the error after restarting my system.
