### ISSUE TITLE
pexpect not working

### ISSUE THREAD

**Issue by arunpersaud** [bpython/bpython#708]
Hello

the following does not work for me and I need to ctrl-c it  (it just hangs)

>>> import pexpect; pexpect.run('ls -l')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pexpect; pexpect.run('ls -l')
  File "/usr/lib/python3.6/site-packages/pexpect/run.py", line 100, in run
    cwd=cwd, env=env, **kwargs)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 197, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 297, in _spawn
    cwd=self.cwd, **kwargs)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 308, in _spawnpty
    return ptyprocess.PtyProcess.spawn(args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 302, in spawn
    exec_err_data = os.read(exec_err_pipe_read, 4096)
  File "/usr/lib/python3.6/site-packages/bpython/curtsiesfrontend/coderunner.py", line 170, in sigint_handler
    raise KeyboardInterrupt()
KeyboardInterrupt
>>> 

I'm using bpython 0.16 on python 3.6.2, running opensuse Tumbleweed. Pexpect work in ipython3 for example on my computer.

**Comment by thomasballinger** [comment]
I should look into this - probably terminal settings that pexpect isn't expecting, but perhaps we could turn them off while we're running code?

**Comment by asergeant01** [comment]
I have encountered this issue as well
