### ISSUE TITLE
Unable to import pandas in bpython

### ISSUE THREAD

**Issue by lidderupk** [bpython/bpython#725]
Hi, 

I am unable to import pandas in bpython.

```
$ bpython
bpython version 0.16 on top of Python 3.6.1 /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
>>> import pandas as pd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/__init__.py", line 59, in <module>
    from pandas.util._tester import test
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/util/_tester.py", line 11, in <module>
    import pytest
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/config.py", line 10, in <module>
    import py
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py/__init__.py", line 151, in <module>
    'Syslog'             : '._log.log:Syslog',
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py/_vendored_packages/apipkg.py", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

Second time:
```
>>> import pandas as pd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/__init__.py", line 51, in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
AttributeError: module 'pandas' has no attribute 'plotting'
```

**Comment by lidderupk** [comment]
I was able to resolve using virtualenv. No idea why it does not work globally. I am using the same version of pandas and pip in both cases.
