### ISSUE TITLE
ValueError inside python:3.6-alpine Docker

### ISSUE THREAD

**Issue by F0x06** [bpython/bpython#737]
Hi, when i start BPython inside my docker shell, it crashed with the following error:

```
bpython version 0.17.1 on top of Python 3.6.4 /usr/local/bin/python

Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsies.py", line 118, in mainloop
    self.process_event_and_paint(None)
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsies.py", line 100, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsiesfrontend/repl.py", line 1356, in paint
    self.current_cursor_line)
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsiesfrontend/replpainter.py", line 47, in paint_current_line
    lines = display_linize(current_display_line, columns, True)
  File "/usr/local/lib/python3.6/site-packages/bpython/curtsiesfrontend/replpainter.py", line 32, in display_linize
    if msg else ([''] if blank_line else []))
ValueError: range() arg 3 must not be zero
```

Thank you.

**Comment by Da-Juan** [comment]
Hi,
I ran into the same error with `debian:9` Docker image and python 2.7.13.

**Comment by Da-Juan** [comment]
Hi,
I ran into the same error with `debian:9` Docker image and python 2.7.13.

**Comment by Da-Juan** [comment]
There's a bug in `docker exec` terminal resizing here: https://github.com/moby/moby/issues/35407

I think I found a workaround...

```bash
# Force setting COLUMNS and LINES bash variables
docker exec -it -e COLUMNS=$COLUMNS -e LINES=$LINES my_container bash
# TTY size is still wrong
root@3ade37b5ae39:/# stty size
0 0
# Reset the terminal
root@3ade37b5ae39:/# reset -w
# TTY size is now goog
root@3ade37b5ae39:/# stty size
57 106 
# It works!                                                                                               
root@3ade37b5ae39:/# source /venv/bin/activate
(venv) root@3ade37b5ae39:/# bpython
bpython version 0.17.1 on top of Python 2.7.13 /venv/bin/python2
>>> 
```
