### ISSUE TITLE
Error while importing six.moves

### ISSUE THREAD

**Issue by CyberSaxosTiGER** [bpython/bpython#738]
suddenly my bpython interpreter stops work

```shell
 ~ % bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 7, in <module>
    from bpython.curtsies import main
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsies.py", line 16, in <module>
    from .curtsiesfrontend.repl import BaseRepl
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 40, in <module>
    from bpython.curtsiesfrontend import replpainter as paint
  File "/usr/local/lib/python2.7/dist-packages/bpython/curtsiesfrontend/replpainter.py", line 6, in <module>
    from six.moves import range
ImportError: cannot import name range
```

but when I try to import  six.moves in normal interpreter no problem. I try to reinstall bpython and six lib but nothing helps

```python console

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from six.moves import range
>>> 
>>> import six
>>> six.__version__
'1.11.0'

```

**Comment by r-dog** [comment]
@CyberSaxosTiGER I'm going to take a wild guess here and say that bpython is confusing the range function you're trying to import with the actual built-in range function. Try this:
`>>> import six.moves as sm
>>> sm.range()
`

**Comment by thomasballinger** [comment]
Closing, this seems to be due to having the wrong version of the six installed.
