### ISSUE TITLE
bpython fails to start on win7 sp1 64bit

### ISSUE THREAD

**Issue by ThrashAbaddon** [bpython/bpython#739]
Using:
```
C:\Users\kusari>pip -v -V
pip 10.0.0 from c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages\pip (python 3.6)
```

```
C:\Users\kusari>pip show bpython
Name: bpython
Version: 0.17.1
Summary: Fancy Interface to the Python Interpreter
Home-page: http://www.bpython-interpreter.org/
Author: Bob Farrell, Andreas Stuehrk et al.
Author-email: robertanthonyfarrell@gmail.com
License: MIT/X
Location: c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages
Requires: pygments, greenlet, six, requests, curtsies
Required-by:
```

```
C:\Users\kusari>bpython
Traceback (most recent call last):
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kusari\AppData\Local\Programs\Python\Python36-32\Scripts\bpython.exe\__main__.py", line 5, in <module>
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages\bpython\curtsies.py", line 11, in <module>
    import curtsies
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages\curtsies\window.py", line 11, in <module>
    import blessings
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "c:\users\kusari\appdata\local\programs\python\python36-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by thomasballinger** [comment]
I think your options are either to:
* download an unofficial curses module from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and bpython won't crash, but also probably won't work?
OR
* use bpython-urwid instead - I think this has better Windows support?
Let us know what you find out, we're short on Windows users to tell us what works or doesn't.

**Comment by kmonson** [comment]
Windows 10 python 3.6.5

bpython.exe:

Traceback (most recent call last):
  File "c:\users\xistic\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xistic\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Xistic\Python36\Scripts\bpython.exe\__main__.py", line 5, in <module>
  File "c:\users\xistic\python36\lib\site-packages\bpython\curtsies.py", line 11, in <module>
    import curtsies
  File "c:\users\xistic\python36\lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "c:\users\xistic\python36\lib\site-packages\curtsies\window.py", line 11, in <module>
    import blessings
  File "c:\users\xistic\python36\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'

bpython-curses.exe

Starts correctly then hitting enter (no input) on the >>> prompt gives this:

Traceback (most recent call last):
  File "c:\users\xistic\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xistic\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Xistic\Python36\Scripts\bpython-curses.exe\__main__.py", line 9, in <module>
  File "c:\users\xistic\python36\lib\site-packages\bpython\cli.py", line 1959, in main
    banner=banner)
  File "c:\users\xistic\python36\lib\site-packages\bpython\cli.py", line 1844, in curses_wrapper
    return func(stdscr, *args, **kwargs)
  File "c:\users\xistic\python36\lib\site-packages\bpython\cli.py", line 1895, in main_curses
    clirepl = CLIRepl(main_win, interpreter, statusbar, config, idle)
  File "c:\users\xistic\python36\lib\site-packages\bpython\cli.py", line 330, in __init__
    repl.Repl.__init__(self, interp, config)
  File "c:\users\xistic\python36\lib\site-packages\bpython\repl.py", line 459, in __init__
    getpreferredencoding() or "ascii")
  File "c:\users\xistic\python36\lib\site-packages\bpython\history.py", line 181, in load
    with FileLock(hfile):
  File "c:\users\xistic\python36\lib\site-packages\bpython\filelock.py", line 56, in __enter__
    self.acquire()
  File "c:\users\xistic\python36\lib\site-packages\bpython\filelock.py", line 100, in acquire
    msvcrt.locking(self.fd, msvcrt.LK_NBLCK, 1)
TypeError: an integer is required (got type _io.TextIOWrapper)

Now every time I try bpython-curses.exe I get the same error at startup.

I get the same error in bpython-urwid.exe at startup. I'm a bpython noob, but I'm guessing it has something to do with prematriggering that same error in the curses version.

**Comment by kmonson** [comment]
Oh, I installed the curses from https://www.lfd.uci.edu/~gohlke/pythonlibs/ before I ran these tests.

**Comment by sebastinas** [comment]
The issue in bpython/filelock.py is fixed on the master branch.

**Comment by shula** [comment]
so... 
1. I installed curses,
2. installed urwid
3. running bpython-urwid:

```
c:\>bpython-urwid.exe
Exception ignored in: <bound method BaseLock.__del__ of <bpython.filelock.WindowsFileLock object at 0x00000000027037F0>>
Traceback (most recent call last):
  File "c:\programs\python3\lib\site-packages\bpython\filelock.py", line 65, in __del__
    self.release()
  File "c:\programs\python3\lib\site-packages\bpython\filelock.py", line 104, in release
    msvcrt.locking(self.fileobj.fileno(), msvcrt.LK_UNLCK, 1)
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "c:\programs\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programs\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\programs\Python3\Scripts\bpython-urwid.exe\__main__.py", line 9, in <module>
  File "c:\programs\python3\lib\site-packages\bpython\urwid.py", line 1230, in main
    myrepl = URWIDRepl(event_loop, palette, interpreter, config)
  File "c:\programs\python3\lib\site-packages\bpython\urwid.py", line 619, in __init__
    input_filter=input_filter, handle_mouse=False)
  File "c:\programs\python3\lib\site-packages\urwid\main_loop.py", line 114, in __init__
    screen = raw_display.Screen()
  File "c:\programs\python3\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

```

**Comment by sebastinas** [comment]
The last issue is fixed on the master branch.

**Comment by williamjamir** [comment]
Hi,
I'm using Windows 10 with `Python 3.5.0 :: Continuum Analytics, Inc.` and every action inside the bpython-curses raises a `ValueError: I/O operation on closed file` exception

Steps that I made:
1) Install curses: 
```Python
pip instal curses-2.2-cp35-cp35m-win_amd64.whl
```
2) Install bpython from master
```Python
(testing) λ pip install git+https://github.com/bpython/bpython
Collecting git+https://github.com/bpython/bpython
  Cloning https://github.com/bpython/bpython to c:\users\william\appdata\local\temp\pip-req-build-c1x30v7k
Requirement already satisfied: pygments in w:\miniconda\envs\testing\lib\site-packages (from bpython==0.17.1.post35) (2.2.0)
Requirement already satisfied: requests in w:\miniconda\envs\testing\lib\site-packages (from bpython==0.17.1.post35) (2.19.1)
Requirement already satisfied: curtsies>=0.1.18 in w:\miniconda\envs\testing\lib\site-packages (from bpython==0.17.1.post35) (0.3.0)
Requirement already satisfied: greenlet in w:\miniconda\envs\testing\lib\site-packages (from bpython==0.17.1.post35) (0.4.14)
Requirement already satisfied: six>=1.5 in w:\miniconda\envs\testing\lib\site-packages (from bpython==0.17.1.post35) (1.11.0)
Requirement already satisfied: idna<2.8,>=2.5 in w:\miniconda\envs\testing\lib\site-packages (from requests->bpython==0.17.1.post35) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in w:\miniconda\envs\testing\lib\site-packages (from requests->bpython==0.17.1.post35) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in w:\miniconda\envs\testing\lib\site-packages (from requests->bpython==0.17.1.post35) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in w:\miniconda\envs\testing\lib\site-packages (from requests->bpython==0.17.1.post35) (1.23)
Requirement already satisfied: typing in w:\miniconda\envs\testing\lib\site-packages (from curtsies>=0.1.18->bpython==0.17.1.post35) (3.6.4)
Requirement already satisfied: blessings>=1.5 in w:\miniconda\envs\testing\lib\site-packages (from curtsies>=0.1.18->bpython==0.17.1.post35) (1.7)
Requirement already satisfied: wcwidth>=0.1.4 in w:\miniconda\envs\testing\lib\site-packages (from curtsies>=0.1.18->bpython==0.17.1.post35) (0.1.7)
Building wheels for collected packages: bpython
  Running setup.py bdist_wheel for bpython ... done
  Stored in directory: C:\Users\william\AppData\Local\Temp\pip-ephem-wheel-cache-j25sjrqg\wheels\48\17\45\35f06eccf6f1d43ad7976b04512ae44d5b05a919a6722e4d59
Successfully built bpython
Installing collected packages: bpython
Successfully installed bpython-0.17.1.post35
```

3) Open `bpython-curses` 
```Python
bpython-curses
```

4) Try to read a value.
```Python
>>> hi = 'Hello'
>>> hi
Exception ignored in: <bound method BaseLock.__del__ of <bpython.filelock.WindowsFileLock object at 0x00000266C4E59518>>
Traceback (most recent call last):
  File "w:\miniconda\envs\testing\lib\site-packages\bpython\filelock.py", line 65, in __del__
    self.release()
  File "w:\miniconda\envs\testing\lib\site-packages\bpython\filelock.py", line 104, in release
    msvcrt.locking(self.fileobj.fileno(), msvcrt.LK_UNLCK, 1)
ValueError: I/O operation on closed file
'Hello'
```

5) Trying to create a function, (I receive the error when I type "tab"):
```Python
>>> def foo():
Exception ignored in: <bound method BaseLock.__del__ of <bpython.filelock.WindowsFileLock object at 0x00000266C4E45630>>
Traceback (most recent call last):
  File "w:\miniconda\envs\testing\lib\site-packages\bpython\filelock.py", line 65, in __del__
    self.release()
  File "w:\miniconda\envs\testing\lib\site-packages\bpython\filelock.py", line 104, in release
    msvcrt.locking(self.fileobj.fileno(), msvcrt.LK_UNLCK, 1)
ValueError: I/O operation on closed file
...     print("hello")
```

**Comment by amzakil** [comment]
> I think your options are either to:
> 
> * download an unofficial curses module from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and bpython won't crash, but also probably won't work?
>   OR
> * use bpython-urwid instead - I think this has better Windows support?
>   Let us know what you find out, we're short on Windows users to tell us what works or doesn't.

It still did not work. I tried bpython-curses and  bpython-urwid. I got the same error, TypeError: an integer is required (got type _io.TextIOWrapper).

**Comment by jfrid** [comment]
I experience the same problem as @shula, i.e. any operation leads to a ValueError:

```python
>>> x = 1
Exception ignored in: <function BaseLock.__del__ at 0x000001F55A24DA60>
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\bpython\filelock.py", line 65, in __del__
    self.release()
  File "c:\program files\python37\lib\site-packages\bpython\filelock.py", line 104, in release
    msvcrt.locking(self.fileobj.fileno(), msvcrt.LK_UNLCK, 1)
ValueError: I/O operation on closed file
```

Running:

* Windows 10 1809
* Python 3.7.2 64-bit
* curses 2.2 cp37
* bpython-curses 0.17.1-51 fetched from master 2019-02-25

**Comment by agmartin** [comment]
I'm having the same problems as @jfrid and @shula. First, there's a typo I think in line 191 of history.py.

`os.TRUNC` should be `os.O_TRUNC`

But there's still some nastiness going on with the FileLock. Windows is throwing permissions errors even though I own the .pythonhist file and the process is running as me..

I'm working on figuring it out since work is kind of slow this week. Will update you and submit a patch for consideration if I figure it out.

**Comment by 108806** [comment]
Same IO error here, cant get it to work on Win10x64 18362.

**Comment by sebastinas** [comment]
Thanks @agmartin. We now use `os.O_TRUNC`. I don't understand why `__del__` is trying to unlock again. It should already unlock in `__exit__`.

**Comment by myrmica-habilis** [comment]
I get the same `ValueError: I/O operation on closed file` when running `bpython-curses.exe`. (Win7 64bit, Python 3.7.5 for Windows)

Both `bpython.exe` and `bpython-urwid.exe` try to access the `fcntl` module, which is not available in Python for Windows, and is not available as an unofficial binary at [www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Comment by myrmica-habilis** [comment]
This seems to have fixed it, although I am not sure why:
https://github.com/myrmica-habilis/bpython/commit/da0a14fede8950cfff9cb46bc73fada3a36c4f13
Can someone please test it?

Simplified example - this code raises the error in question:
```
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import msvcrt
>>>
>>> with open('.pythonhist') as f:
...     msvcrt.locking(f.fileno(), msvcrt.LK_NBLCK, 1)
...     print(f.read(1))
...     msvcrt.locking(f.fileno(), msvcrt.LK_UNLCK, 1)
...
p
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
PermissionError: [Errno 13] Permission denied
```
as opposed to:
```
>>>
>>> with open('.pythonhist') as f:
...     msvcrt.locking(f.fileno(), msvcrt.LK_NBLCK, 1)
...     print(f.read(1))
...     f.seek(0)
...     msvcrt.locking(f.fileno(), msvcrt.LK_UNLCK, 1)
...
p
0
>>>
```

**Comment by sebastinas** [comment]
Ah, I see. I have used `msvcrt.locking` incorrectly. Should be fixed in `52580b4`.

**Comment by myrmica-habilis** [comment]
Looks good, except that `release` now tries to call a `close` method on an integer file descriptor `self.fileobj`:
```python
  File "c:\home\michal\github_forks\bpython\bpython\filelock.py", line 114, in release
    self.fileobj.close()
AttributeError: 'int' object has no attribute 'close'
```
I created a pull request fixing this, together with a test case for the methods that use FileLock. Feel free to accept or reject it. Thanks.
