### ISSUE TITLE
bpython error with Flask-SQLAlchemy session

### ISSUE THREAD

**Issue by newbigland** [bpython/bpython#741]
I encountered a bpython error with Flask-SQLAlchemy session when I was learning a book named Flask Web Development written by Miguel Grinberg. the python version is 3.5.4, test code is here:
➜  flasky-first-edition git:(b110bbf) python3 hello.py shell

`>>>` from hello import db
`>>>` db.create_all()
`>>>` from hello import Role,User
`>>>` admin_role = Role(name='Admin')
`>>>` user_john = User(username='john', role= admin_role)
`>>>` print(admin_role.id)
None
`>>>` db.session.add(admin_role)
`>>>` db.session.add(user_john)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    db.session.add(user_john)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 1
53, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1
776, in add
    self._save_or_update_state(state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1
789, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2
104, in _save_or_update_impl
    self._save_impl(state)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2
056, in _save_impl
    to_attach = self._before_attach(state, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2
179, in _before_attach
    state.session_id, self.hash_key))
sqlalchemy.exc.InvalidRequestError: Object '<User at 0x105284320>' is already attached to session '1' (this is '2')
`>>>`
But when I uninstall bpython (version 0.17.1), It is successful to execute the code in the python interpreter or in ipython or ptpython. It seems to be a bug in bpython.

**Comment by thomasballinger** [comment]
Sorry you ran into this! Other people have run into it too, see  https://github.com/bpython/bpython/issues/676. The solution is probably to move back to threads. In the meantime, try bpython-curses, which shouldn't have this problem.
