### ISSUE TITLE
xrange() arg 3 must not be zero

### ISSUE THREAD

**Issue by fkoester** [bpython/bpython#742]
I am using Django 1.11 and bpython 0.17.1 on Python 2.7 and when running `./manage.py shell_plus` I get the following error:

```python
Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    execute_from_command_line(sys.argv)
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 85, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "/app/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/app/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/app/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 476, in handle
    shell()
  File "/app/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 264, in run_bpython
    embed(imported_objects, **kwargs)
  File "/app/local/lib/python2.7/site-packages/bpython/__init__.py", line 38, in embed
    return main(args, locals_, banner)
  File "/app/local/lib/python2.7/site-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/app/local/lib/python2.7/site-packages/bpython/curtsies.py", line 118, in mainloop
    self.process_event_and_paint(None)
  File "/app/local/lib/python2.7/site-packages/bpython/curtsies.py", line 100, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/app/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1356, in paint
    self.current_cursor_line)
  File "/app/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 47, in paint_current_line
    lines = display_linize(current_display_line, columns, True)
  File "/app/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/replpainter.py", line 32, in display_linize
    if msg else ([''] if blank_line else []))
ValueError: xrange() arg 3 must not be zero
```

**Comment by thomasballinger** [comment]
Hm seems like width is zero here, I should repro with django to see why this is the case.

**Comment by thomasballinger** [comment]
With the following pip freeze output
```
(django-example) tomb@tom-mbp ~$ pip freeze
blessings==1.7
bpython==0.17.1
certifi==2018.4.16
chardet==3.0.4
curtsies==0.3.0
Django==1.11.14
django-extensions==2.0.7
greenlet==0.4.13
idna==2.7
Pygments==2.2.0
pytz==2018.5
requests==2.19.1
six==1.11.0
typing==3.6.4
urllib3==1.23
wcwidth==0.1.7
```
I can't repro this - anything else that might be different about our environments? What terminal emulator are you running? What operating system?

It looks like columns zero somehow, maybe the way we query for terminal size isn't working. We could add an assertion that columns isn't zero somewhere earlier in the program flow.

**Comment by sebastinas** [comment]
Closing for now. Please provide the additional info requested by @thomasballinger if the issue still exists.

**Comment by radusuciu** [comment]
Same error, running in docker (image based on `debian:bullseye-slim`, WSL2, Windows 10), either in Windows Terminal or VSCode 1.68.1. Works with `ipython`, though it could still be a `django-extensions` issue.

My installed deps:
```toml
# pyproject.toml snippet
requires-python = ">=3.9,<4.0"
dependencies = [
    "Django<4.0.0,>=3.2.8",
    "requests>=2.27.1",
    "biblib @ git+https://github.com/radusuciu/biblib",
    "django-ninja<1.0.0,>=0.16.1",
    "django-eav2<2.0.0,>=1.1.0",
    "django-pgtrigger<3.0.0,>=2.4.0",
    "django-rdkit @ git+https://github.com/rdkit/django-rdkit.git",
    "django-admin-interface>=0.19.1",
    "django-extensions>=3.1.5",
    "bpython>=0.22.1",
]
```

Here is the error:
```bash
$ python manage.py shell_plus --bpython
# Shell Plus Model Imports
from admin_interface.models import Theme
from chompounddb.models import Aliquot, Compound, CompoundAttachment, CompoundBatch, CompoundRequest, CompoundRequestItem, LiteratureReference, Plate, User
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from eav.models import Attribute, EnumGroup, EnumValue, Value
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When
from django.utils import timezone
from django.urls import reverse
from django.db.models import Exists, OuterRef, Subquery

Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 25, in display_linize
    display_lines = list(msg.width_aware_splitlines(columns))
  File "/venv/lib/python3.9/site-packages/curtsies/formatstring.py", line 674, in width_aware_splitlines
    raise ValueError("Column width %s is too narrow." % columns)
ValueError: Column width 0 is too narrow.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 125, in run_from_argv
    return super().run_from_argv(argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.9/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 586, in handle
    runner()
  File "/venv/lib/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 397, in run_bpython
    embed(imported_objects, **kwargs)
  File "/venv/lib/python3.9/site-packages/bpython/__init__.py", line 45, in embed
    return main(args, locals_, banner)
  File "/venv/lib/python3.9/site-packages/bpython/curtsies.py", line 248, in main
    repl.mainloop(True, paste)
  File "/venv/lib/python3.9/site-packages/bpython/curtsies.py", line 173, in mainloop
    self.process_event_and_paint(None)
  File "/venv/lib/python3.9/site-packages/bpython/curtsies.py", line 151, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/venv/lib/python3.9/site-packages/bpython/curtsiesfrontend/repl.py", line 1489, in paint
    current_line = paint.paint_current_line(
  File "/venv/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 49, in paint_current_line
    lines = display_linize(current_display_line, columns, True)
  File "/venv/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 31, in display_linize
    range(0, len(msg), columns),
ValueError: range() arg 3 must not be zero
```

**Comment by radusuciu** [comment]
Well that was fast... I figured that the only non-bleeding edge dependency I was using was docker... so I upgraded to Docker version 20.10.16, build aa7e414 (Docker Desktop for Windows, used through WSL2) and the problem was magically fixed.
