### ISSUE TITLE
Gracefully handle errors during print()

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#747]
bpython does not gracefully handle errors while printing.

For example, when trying to print an invalid character, stock python raises an exception, but does not exit the shell.  bpython raises an exception, which crashes the shell and confuses the terminal.

Expected behavior: Pretty-print the exception, stay within the shell.
Actual behavior: Ugly-print the exception revealing bpython-internals, closes shell, and leaves terminal in a weird state (invisible cursor).

Minimal example:

```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print('\udcfc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfc' in position 0: surrogates not allowed
>>> 1+1
2
>>> quit()
[$? = 0]

$ bpython3
bpython version 0.16 on top of Python 3.5.3 /usr/bin/python3
>>> print('\udcfc')

Traceback (most recent call last):
  File "/usr/bin/bpython3", line 11, in <module>
    load_entry_point('bpython==0.16', 'console_scripts', 'bpython')()
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 190, in main
    exit_value = repl.mainloop()
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(e)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 100, in process_event_and_paint
    scrolled = self.window.render_to_terminal(array, cursor_pos)
  File "/usr/lib/python3/dist-packages/curtsies/window.py", line 412, in render_to_terminal
    self.write(for_stdout(line))
  File "/usr/lib/python3/dist-packages/curtsies/window.py", line 43, in write
    self.out_stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfc' in position 0: surrogates not allowed
[$? = 1]
```

**Comment by BenWiederhake** [comment]
Then your terminal probably doesn't support it, and you may have more luck with a different one.

I'm not saying that the bug is *due* to your terminal, just that a different terminal won't trigger the bug in bpython.

**Comment by belgiancoder** [comment]
You know what, I updated my terminal this morning and :
```
>>> print('\udcfc')
�
```
No error anymore.

**Comment by belgiancoder** [comment]
Getting weirder:
```
➜  ~ bpy
bpython version 0.17.1 on top of Python 3.7.2 /usr/local/opt/python/bin/python3.7
>>> try:
...     print('\ud83d')
... except:pass
...

Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/lib/python3.7/site-packages/bpython/curtsies.py", line 126, in mainloop
    self.process_event_and_paint(e)
  File "/usr/local/lib/python3.7/site-packages/bpython/curtsies.py", line 101, in process_event_and_paint
    scrolled = self.window.render_to_terminal(array, cursor_pos)
  File "/usr/local/lib/python3.7/site-packages/curtsies/window.py", line 412, in render_to_terminal
    self.write(for_stdout(line))
  File "/usr/local/lib/python3.7/site-packages/curtsies/window.py", line 43, in write
    self.out_stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed
➜  ~
```
The error is impossible to catch...

**Comment by allgo27** [comment]
I've been able to replicate this error, and discovered that you can catch it in curtsies window.py by adding a try/catch in [write()](https://github.com/bpython/curtsies/blob/ae514404b01432cf3a7f1a69c8c581a5c1cc3967/curtsies/window.py#L65-L70), but it feels like we should be catching the errors before we hit curtsies...

**Comment by thomasballinger** [comment]
Bpython passes unicode strings to Curtsies, which encodes them to print them. I think as part of the callstack of the user code, we should call encode and let the error occur normally. This means we'll need to know what encoding Curtsies is going to use to print the characters; I expect this is however locale works currently in bpython.

**Comment by AustinTSchaffer** [comment]
This seems related to an issue I'm seeing today as well. It seems like I can print an emoji if I import it from a file, but I can't paste an emoji *into* the REPL. Simple demo below. I triggered the exception by pasting a single `❓` emoji into the terminal.

![image](https://user-images.githubusercontent.com/16184219/108245601-7886f480-711e-11eb-97c2-6e7cd052e080.png)

Stack trace text:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mac/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/mac/lib/python3.6/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/opt/anaconda3/envs/mac/lib/python3.6/site-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/opt/anaconda3/envs/mac/lib/python3.6/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/opt/anaconda3/envs/mac/lib/python3.6/site-packages/bpython/curtsiesfrontend/repl.py", line 1615, in paint
    self.cursor_offset,
AssertionError: (-1, 269, 5, 1, 1)
```
