### ISSUE TITLE
"Save to file" not working

### ISSUE THREAD

**Issue by jesrui** [bpython/bpython#759]
In bpython 0.17.1 (Linux) I get the following while trying to save to a file (Control-S):
```
Traceback (most recent call last):
  File "/usr/bin/bpython-curses", line 11, in <module>
    load_entry_point('bpython==0.17.1', 'console_scripts', 'bpython-curses')()
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 1959, in main
    banner=banner)
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 1844, in curses_wrapper
    return func(stdscr, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 1926, in main_curses
    exit_value = clirepl.repl()
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 1126, in repl
    inp = self.get_line()
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 671, in get_line
    if self.p_key(key) is None:
  File "/usr/lib/python3.7/site-packages/bpython/cli.py", line 957, in p_key
    self.write2file()
  File "/usr/lib/python3.7/site-packages/bpython/repl.py", line 845, in write2file
    f.write(stdout_text)
NameError: name 'stdout_text' is not defined
```
After Control-S, I get a message asking for a filename to save to, then the error above. Same with bpython-curses. Same with python2.

**Comment by sebastinas** [comment]
This is already fixed on the master branch.
