### ISSUE TITLE
ModuleNotFoundError when running bpython

### ISSUE THREAD

**Issue by sc-1123** [bpython/bpython#780]
Throws error:

Traceback (most recent call last):
  File "d:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python36\Scripts\bpython.exe\__main__.py", line 5, in <module>
  File "d:\python36\lib\site-packages\bpython\curtsies.py", line 11, in <module>
    import curtsies
  File "d:\python36\lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "d:\python36\lib\site-packages\curtsies\window.py", line 11, in <module>
    import blessings
  File "d:\python36\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "d:\python36\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by sebastinas** [comment]
Did you install `curses` as recommended in the `CLI Windows support` section?

**Comment by sc-1123** [comment]
Sorry that I'm too busy to see this. After I saw this error, I used `curses` unofficial binary to install it.
Then I found that bpython needs fcntl, so I made a fake fcntl module.
Well, it said that it need a module `termios` .

**Comment by sebastinas** [comment]
If you have installed `curses`, then 'bpython-cli` should work. `fcntl` is only required for the `curtsies` frontend (by a dependency).

**Comment by elig0n** [comment]
@sebastinas  How to get 'fcntl' ? 
@sc-1123  can you explain how did you fake 'fnctl' ?

**Comment by sebastinas** [comment]
I don't think you can get `fcntl` on Windows.

**Comment by johnd0e** [comment]
See https://github.com/bpython/bpython/issues/509#issuecomment-860573706

**Comment by abubelinha** [comment]
> Did you install `curses` as recommended in the `CLI Windows support` section?

@sebastinas I did, and also saw #509 and #649
But still getting errors:

```
C:\Python38\scripts\pip install C:\soft\Python\wheels\curses-2.2.1+utf8-cp38-cp38-win_amd64.whl
Processing c:\soft\python\wheels\curses-2.2.1+utf8-cp38-cp38-win_amd64.whl
Installing collected packages: curses
Successfully installed curses-2.2.1+utf8

C:\Python38\scripts\pip install bpython
(...)
Successfully installed bpython-0.22.1

c:\Python38\scripts\bpython-curses
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:Python38\scripts\bpython-curses.exe\__main__.py", line 4, in <module>
  File "c:python38\lib\site-packages\bpython\cli.py", line 71, in <module>
    from .config import getpreferredencoding
  File "c:python38\lib\site-packages\bpython\config.py", line 38, in <module>
    from .curtsiesfrontend.parse import CNAMES
  File "c:\python38\lib\site-packages\bpython\curtsiesfrontend\parse.py", line 3, in <module>
    from curtsies.formatstring import fmtstr, FmtStr
  File "c:\python38\lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "c:\python38\lib\site-packages\curtsies\window.py", line 24, in <module>
    import blessings
  File "c:\python38\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'
```
