### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by jean** [bpython/bpython#796]
Tab-completion raises an exception when completing dictionary keys.
I couldn't reproduce it with a simple dictionary (unsuprisingly ;-)).

```
>>> cpu_dd['Quad Core Co
Traceback (most recent call last):
  File "/home/jean/.local/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsies.py", line 126, in mainloop
    self.process_event_and_paint(e)
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsies.py", line 90, in process_event_and_paint
    self.process_event(e)
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsiesfrontend/repl.py", line 595, in process_event
    return self.process_key_event(e)
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsiesfrontend/repl.py", line 726, in process_key_event
    self.on_tab()
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsiesfrontend/repl.py", line 841, in on_tab
    cursor_and_line = self.matches_iter.substitute_cseq()
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/repl.py", line 332, in substitute_cseq
    self.update(new_cursor_offset, new_line, self.matches,
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/repl.py", line 352, in update
    self.start, self.end, self.current_word = self.completer.locate(
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by jean** [comment]
Looks like this is probably a duplicate of https://github.com/bpython/bpython/issues/726 though the traceback gets one call further.

**Comment by sebastinas** [comment]
Let's use #726 for this issue.
