### ISSUE TITLE
Python 3.9 test failures

### ISSUE THREAD

**Issue by mgorny** [bpython/bpython#809]
A few tests fail on Python 3.9.0b1:

```pytb
======================================================================
ERROR: test_nonsense (bpython.test.test_simpleeval.TestEvaluateCurrentExpression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/simpleeval.py", line 230, in evaluate_current_expression
    return simple_eval(largest_ast, namespace)
  File "/tmp/bpython/bpython/simpleeval.py", line 167, in simple_eval
    return _convert(node_or_string)
  File "/tmp/bpython/bpython/simpleeval.py", line 165, in _convert
    raise ValueError("malformed string")
ValueError: malformed string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 129, in test_nonsense
    self.assertEvaled("--- [2][0].a|bc", 2)
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 107, in assertEvaled
    evaluate_current_expression(cursor_offset, line, ns), value
  File "/tmp/bpython/bpython/simpleeval.py", line 232, in evaluate_current_expression
    raise EvaluationError("Could not safely evaluate")
bpython.simpleeval.EvaluationError: Could not safely evaluate

======================================================================
ERROR: test_with_namespace (bpython.test.test_simpleeval.TestEvaluateCurrentExpression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/simpleeval.py", line 230, in evaluate_current_expression
    return simple_eval(largest_ast, namespace)
  File "/tmp/bpython/bpython/simpleeval.py", line 167, in simple_eval
    return _convert(node_or_string)
  File "/tmp/bpython/bpython/simpleeval.py", line 165, in _convert
    raise ValueError("malformed string")
ValueError: malformed string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 134, in test_with_namespace
    self.assertEvaled("a[1].a|bc", "d", {"a": "adsf"})
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 107, in assertEvaled
    evaluate_current_expression(cursor_offset, line, ns), value
  File "/tmp/bpython/bpython/simpleeval.py", line 232, in evaluate_current_expression
    raise EvaluationError("Could not safely evaluate")
bpython.simpleeval.EvaluationError: Could not safely evaluate

======================================================================
ERROR: Literals can be indexed into
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 28, in test_indexing
    self.assertEqual(simple_eval("[1,2][0]"), 1)
  File "/tmp/bpython/bpython/simpleeval.py", line 167, in simple_eval
    return _convert(node_or_string)
  File "/tmp/bpython/bpython/simpleeval.py", line 165, in _convert
    raise ValueError("malformed string")
ValueError: malformed string

======================================================================
ERROR: Names can be lookup up in a namespace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_simpleeval.py", line 35, in test_name_lookup
    self.assertEqual(simple_eval("a[b]", {"a": {"c": 1}, "b": "c"}), 1)
  File "/tmp/bpython/bpython/simpleeval.py", line 167, in simple_eval
    return _convert(node_or_string)
  File "/tmp/bpython/bpython/simpleeval.py", line 165, in _convert
    raise ValueError("malformed string")
ValueError: malformed string

======================================================================
FAIL: test_att_matches_found_on_instance (bpython.test.test_autocomplete.TestExpressionAttributeCompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_autocomplete.py", line 316, in test_att_matches_found_on_instance
    self.assertSetEqual(
AssertionError: Items in the second set but not the first:
'method'
'a'
'b'

======================================================================
FAIL: test_dictionaries_complete (bpython.test.test_autocomplete.TestExpressionAttributeCompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_autocomplete.py", line 365, in test_dictionaries_complete
    self.assertSetEqual(
AssertionError: Items in the second set but not the first:
'method'
'a'
'b'

======================================================================
FAIL: test_literals_complete (bpython.test.test_autocomplete.TestExpressionAttributeCompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_autocomplete.py", line 359, in test_literals_complete
    self.assertSetEqual(
AssertionError: Items in the second set but not the first:
'method'
'a'
'b'

======================================================================
FAIL: test_tuples_complete (bpython.test.test_autocomplete.TestExpressionAttributeCompletion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bpython/bpython/test/test_autocomplete.py", line 336, in test_tuples_complete
    self.assertSetEqual(
AssertionError: Items in the second set but not the first:
'method'
'a'
'b'

----------------------------------------------------------------------
Ran 329 tests in 12.934s

FAILED (SKIP=27, errors=4, failures=4)
```

**Comment by tirkarthi** [comment]
the ast related errors raising malformed errors on `ast.Subscript` could be due to https://bugs.python.org/issue40430
