### ISSUE TITLE
Undo after interactive help() crashes

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#822]
~~~
tomb (master) audioembed$ bpython
bpython version 0.20.dev11 on top of Python 3.8.2 /Users/tomb/.pyenv/versions/3.8.2/bin/python3.8
>>> help()

Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
>>> 1
1
>>> ctrl-R
```

**Comment by sebastinas** [comment]
How does it crash? I cannot reproduce it (with Python 3.6).

**Comment by thomasballinger** [comment]
![2020-07-16 09 38 10](https://user-images.githubusercontent.com/458879/87691803-de9e3a00-c73f-11ea-86aa-3e39c8819366.gif)

**Comment by thomasballinger** [comment]
~~~
Traceback (most recent call last):
  File "/Users/tomb/.pyenv/versions/3.8.2/bin/bpython", line 33, in <module>
    sys.exit(load_entry_point('bpython', 'console_scripts', 'bpython')())
  File "/Users/tomb/bpython/bpython/curtsies.py", line 220, in main
    exit_value = repl.mainloop(True, paste)
  File "/Users/tomb/bpython/bpython/curtsies.py", line 132, in mainloop
    self.process_event_and_paint(e)
  File "/Users/tomb/bpython/bpython/curtsies.py", line 96, in process_event_and_paint
    self.process_event(e)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 630, in process_event
    return self.process_control_event(e)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 688, in process_control_event
    self.undo(n=e.n)
  File "/Users/tomb/bpython/bpython/repl.py", line 1018, in undo
    self.reevaluate()
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 1858, in reevaluate
    self.on_enter(new_code=new_code)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 875, in on_enter
    self.push(self.current_line, insert_into_history=new_code)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 1177, in push
    self.coderunner.load_code(code_to_run)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/coderunner.py", line 116, in load_code
    assert self.source is None, (
AssertionError: you shouldn't load code when some is already running
~~~
