### ISSUE TITLE
`print()` in a loop doesn't output until the loop is done

### ISSUE THREAD

**Issue by jean** [bpython/bpython#825]
I paste some code into the BPython REPL. 
It looks like nothing happened, I don't even see the code I pasted, but it is running. 

When I interrupt the loop, all this appears at once:

```python
>>> import time
>>> 
>>> # seen_nodes = []
>>> # dupe_nodes = []
>>> counter = 0
>>> for row in col.get_rows():
...     node_id = row.get_property('node_id') 
...     if (node_id in seen_nodes) and (node_id not in dupe_nodes):
...         dupe_nodes.append(node_id)
...     elif node_id not in seen_nodes:
...         seen_nodes.append(node_id)
...     counter += 1
...     if not counter % 2:
...         print(f'{counter:6} | seen: {len(seen_nodes)}, dupes: {len(dupe_nodes)}', flush=True)
...         time.sleep(1)
... 
     2 | seen: 12530, dupes: 100
     4 | seen: 12530, dupes: 102
     6 | seen: 12530, dupes: 104
     8 | seen: 12530, dupes: 106
Traceback (most recent call last):
  File "<input>", line 10, in <module>
    time.sleep(1)
  File "/home/jean/.local/lib/python3.8/site-packages/bpython/curtsiesfrontend/coderunner.py", line 176, in sigint_handler
    raise KeyboardInterrupt()
KeyboardInterrupt

**Comment by etiennerichart** [comment]
Hey Jean, I can't reproduce this. Maybe it's something else in the rest of your code. Could you share it with us? Also, what version of bpython are you using?

**Comment by thomasballinger** [comment]
Oh I missed a critical detail here, this is *only when you paste the code in.*

Here's a smaller repro: copy this code and paste it into bpython.

```
import time
for i in range(10):
    print(i)
    time.sleep(.1)

print('done')
~~~

**Comment by mahnerak** [comment]
@sebastinas  I've just tried this. It really freezes until the command finishes, and outputs only after it's done.

Are there any config / history files that may affect this?

**Comment by sebastinas** [comment]
No, it's a bug.

**Comment by sebastinas** [comment]
No idea. I haven't looked at this bug (or the pasting code) at all.
