### ISSUE TITLE
Resizing terminal while editor open crashes bpython

### ISSUE THREAD

**Issue by thomasballinger** [bpython/bpython#827]
start bpython, enter a line, F7, change the size of the terminal

**Comment by sebastinas** [comment]
#65 again?

**Comment by thomasballinger** [comment]
Not quite I think, it's much easier to reproduce for one. I can look into this more after work hours.
~~~
    1 ### current bpython session - make changes and save to reevaluate session.
Traceback (most recent call last):
  File "/Users/tomb/.pyenv/versions/3.8.2/bin/bpython", line 33, in <module>
    sys.exit(load_entry_point('bpython', 'console_scripts', 'bpython')())
  File "/Users/tomb/bpython/bpython/curtsies.py", line 220, in main
    exit_value = repl.mainloop(True, paste)
  File "/Users/tomb/bpython/bpython/curtsies.py", line 132, in mainloop
    self.process_event_and_paint(e)
  File "/Users/tomb/bpython/bpython/curtsies.py", line 96, in process_event_and_paint
    self.process_event(e)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 643, in process_event
    return self.process_key_event(e)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 798, in process_key_event
    self.send_session_to_external_editor()
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 1016, in send_session_to_external_editor
    text = self.send_to_external_editor(for_editor)
  File "/Users/tomb/bpython/bpython/repl.py", line 1158, in send_to_external_editor
^[[1;7R    if subprocess.call(args) == 0:
  File "/Users/tomb/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/Users/tomb/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/Users/tomb/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Users/tomb/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/Users/tomb/bpython/bpython/curtsiesfrontend/repl.py", line 605, in sigwinch_handler
    cursor_dy = self.get_cursor_vertical_diff()
  File "/Users/tomb/bpython/bpython/curtsies.py", line 78, in get_cursor_vertical_diff
    return self.window.get_cursor_vertical_diff()
  File "/Users/tomb/src/curtsies/curtsies/window.py", line 411, in get_cursor_vertical_diff
    cursor_dy += self._get_cursor_vertical_diff_once()
  File "/Users/tomb/src/curtsies/curtsies/window.py", line 420, in _get_cursor_vertical_diff_once
    row, col = self.get_cursor_position()
  File "/Users/tomb/src/curtsies/curtsies/window.py", line 355, in get_cursor_position
    c = retrying_read()
  File "/Users/tomb/src/curtsies/curtsies/window.py", line 340, in retrying_read
    raise ValueError(
ValueError: ("Stream should be blocking - should't return ''. Returned %r so far", ('',))
~~~
