### ISSUE TITLE
Run crasher tests with curtsies

### ISSUE THREAD

**Issue by sebastinas** [bpython/bpython#878]
Currently it is not possible to run the crasher tests with curtsies. The tests simply hang until they are killed by pytest. @thomasballinger Do you have an idea what could go wrong there?

**Comment by snimark** [comment]
Is this the same problem as this:

```
% bpython
bpython version 0.21 on top of Python 3.9.1 /usr/local/opt/python@3.9/bin/python3.9
>>> help
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 118, in mainloop
    self.process_event_and_paint(e)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/repl.py", line 1644, in paint
    infobox = paint.paint_infobox(
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 201, in paint_infobox
    formatted_argspec(funcprops, arg_pos, width, config)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 103, in formatted_argspec
    punctuation_color = func_for_letter(config.color_scheme["punctuation"])
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/parse.py", line 32, in func_for_letter
    return partial(fmtstr, fg=CNAMES[l.lower()], bold=l.isupper())
KeyError: 'yy'
```

When in bpython and typing `help()`, it pukes when typing the left parenthesis.

**Comment by sebastinas** [comment]
@snimark No, that's a different bug. Could you please file a new one?

**Comment by thomasballinger** [comment]
It looks like it's something with not getting reading enough input, I'll look into it.
