### ISSUE TITLE
KeyError 'yy' when trying invoke help()

### ISSUE THREAD

**Issue by snimark** [bpython/bpython#882]
For `bpython 0.21`, I merely open up the interpreter and type `help()`. As soon as I type the left parenthesis, it spits out the `KeyError`.

I am on a MacBook using Catalina and have installed bpython using homebrew.

```
 % bpython --version
bpython version 0.21 on top of Python 3.9.1 /usr/local/opt/python@3.9/bin/python3.9
(C) 2008-2020 Bob Farrell, Andreas Stuehrk, Sebastian Ramacher, Thomas Ballinger, et al. See AUTHORS.rst for details.

>>> help
Traceback (most recent call last):
  File "/usr/local/Cellar/bpython/0.21/libexec/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsies.py", line 118, in mainloop
    self.process_event_and_paint(e)
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsiesfrontend/repl.py", line 1644, in paint
    infobox = paint.paint_infobox(
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 201, in paint_infobox
    formatted_argspec(funcprops, arg_pos, width, config)
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 103, in formatted_argspec
    punctuation_color = func_for_letter(config.color_scheme["punctuation"])
  File "/usr/local/Cellar/bpython/0.21/libexec/lib/python3.9/site-packages/bpython/curtsiesfrontend/parse.py", line 32, in func_for_letter
    return partial(fmtstr, fg=CNAMES[l.lower()], bold=l.isupper())
KeyError: 'yy'
```

**Comment by sebastinas** [comment]
As of f924f2c7867ed0816b0314d4702a7805ad6014ca you'll get an error message that the theme config is invalid. yy is not a valid color code.

**Comment by snimark** [comment]
Oh, dang! I'm an idiot. I didn't even know that file had been modified.
