### ISSUE TITLE
Fresh bpython install throws error: "TypeError: 'PosixPath' object is not iterable"

### ISSUE THREAD

**Issue by maiamcc** [bpython/bpython#887]
Using Python 3.6.0, started a fresh virtualenv and installed bpython; tried to run it, and got the following error:
```
$ bpython
Traceback (most recent call last):
  File "/Users/maia/code/scratch/scratch/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/Users/maia/code/scratch/scratch/lib/python3.6/site-packages/bpython/curtsies.py", line 150, in main
    curtsies_arguments,
  File "/Users/maia/code/scratch/scratch/lib/python3.6/site-packages/bpython/args.py", line 151, in parse
    loadini(config, options.config)
  File "/Users/maia/code/scratch/scratch/lib/python3.6/site-packages/bpython/config.py", line 186, in loadini
    config.read(config_path)
  File "/Users/maia/.pyenv/versions/3.6.0/lib/python3.6/configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'PosixPath' object is not iterable
```

In case it's relevant:
```
$ which python
/Users/maia/code/scratch/scratch/bin/python
$ python --version
Python 3.6.0
$ which pip
/Users/maia/code/scratch/scratch/bin/pip
$ pip --version
pip 21.0.1 from /Users/maia/code/scratch/scratch/lib/python3.6/site-packages/pip (python 3.6)
```

I'm running MacOS v11.0.1. Any advice?

**Comment by maiamcc** [comment]
Annnnd updating Python fixed it, never mind 😅 

![homer hedge](https://user-images.githubusercontent.com/6332648/110670251-2ffdac80-819b-11eb-9a69-92d5c5da5243.gif)
