### ISSUE TITLE
ModuleNotFoundError: No module named 'filelock'

### ISSUE THREAD

**Issue by dzg** [bpython/bpython#912]
Just starting using this, and it's beautiful! But:

```
$ bpython
bpython version 0.21 on top of Python 3.9.4 /usr/local/Cellar/bpython/0.21/libexec/bin/python3
>>> import mintapi
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import mintapi
  File "/usr/local/lib/python3.9/site-packages/mintapi/__init__.py", line 1, in <module>
    from .api import Mint
  File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 32, in <module>
    from seleniumrequests import Chrome
  File "/usr/local/lib/python3.9/site-packages/seleniumrequests/__init__.py", line 3, in <module>
    from seleniumrequests.request import RequestMixin
  File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 8, in <module>
    import tldextract
  File "/usr/local/lib/python3.9/site-packages/tldextract/__init__.py", line 3, in <module>
    from .tldextract import extract, TLDExtract
  File "/usr/local/lib/python3.9/site-packages/tldextract/tldextract.py", line 59, in <module>
    from .cache import DiskCache, get_cache_dir
  File "/usr/local/lib/python3.9/site-packages/tldextract/cache.py", line 11, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
```

It works fine using `python3` ... on macOS.

Thanks!

**Comment by sebastinas** [comment]
I'm afraid that this is not a bpython issue but an odditiy of the environment you're using. That seems to be mixing a local install of bpython in `/usr/local/Cellar/` with the global install path for Python modules.
