### ISSUE TITLE
Index Error when editing session (F7)

### ISSUE THREAD

**Issue by arian-deimling** [bpython/bpython#913]
Steps to recreate error:
1. run `bpython`
2. press F7 to edit the session
3. remove all contents of the session file (including autogenerated comments)
4. save file and close the text editor

Using `emacs` as my text editor.

```
~ % bpython
bpython version 0.21 on top of Python 3.8.2 /Library/Developer/CommandLineTools/usr/bin/python3
>>> 
Traceback (most recent call last):
  File "/Users/arian/Library/Python/3.8/bin/bpython", line 8, in <module>
    sys.exit(main())
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsies.py", line 85, in process_event_and_paint
    self.process_event(e)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsiesfrontend/repl.py", line 615, in process_event
    return self.process_key_event(e)
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsiesfrontend/repl.py", line 771, in process_key_event
    self.send_session_to_external_editor()
  File "/Users/arian/Library/Python/3.8/lib/python/site-packages/bpython/curtsiesfrontend/repl.py", line 998, in send_session_to_external_editor
    if lines[-1].startswith("### "):
IndexError: list index out of range
```

**Comment by sebastinas** [comment]
Fixed in 87a85dff224b50f28ac7558f728afe9902f67457.
