### ISSUE TITLE
missing typing_extensions dependency in 0.22 release

### ISSUE THREAD

**Issue by dtrodrigues** [bpython/bpython#938]
```
# bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 5, in <module>
    from bpython.curtsies import main
  File "/usr/local/lib/python3.10/site-packages/bpython/curtsies.py", line 16, in <module>
    from . import args as bpargs, translations, inspection
  File "/usr/local/lib/python3.10/site-packages/bpython/args.py", line 47, in <module>
    from .config import default_config_path, Config
  File "/usr/local/lib/python3.10/site-packages/bpython/config.py", line 37, in <module>
    from .autocomplete import AutocompleteModes
  File "/usr/local/lib/python3.10/site-packages/bpython/autocomplete.py", line 50, in <module>
    from . import inspection
  File "/usr/local/lib/python3.10/site-packages/bpython/inspection.py", line 31, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by sebastinas** [comment]
Thanks, fixed in 532dac009bc1c7f64012c7c66c75ffdd4da49275.
