### ISSUE TITLE
input() raises TypeError after running into EOF once

### ISSUE THREAD

**Issue by BenWiederhake** [bpython/bpython#951]
### Steps to reproduce:
- All of this in `bpython`, the same single instance:
- Type `input()`, press enter
- Press Ctrl-D (this should raise an EOFError and return you to the prompt)
- Type `input()`, press enter

### Expected behavior:
```
$ bpython
bpython version 0.21 on top of Python 3.9.9 /usr/bin/python3
>>> input()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    input()
EOFError: EOF when reading a line
>>> input()
```
… and then it's just waiting for something to appear on stdin.

### Actual behavior:
```
$ bpython
bpython version 0.21 on top of Python 3.9.9 /usr/bin/python3
>>> input()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    input()
EOFError: EOF when reading a line
>>> input()
Traceback (most recent call last):
  File "/usr/bin/bpython", line 33, in <module>
    sys.exit(load_entry_point('bpython==0.21', 'console_scripts', 'bpython')())
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 201, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 121, in mainloop
    self.process_event_and_paint(e)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 95, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/lib/python3/dist-packages/bpython/curtsiesfrontend/repl.py", line 1575, in paint
    wcswidth(self.current_stdouterr_line)
TypeError: Argument 'pwcs' has incorrect type (expected str, got FmtStr)
[$? = 1]
```
… and then you're back to the Terminal shell. bpython is dead.

I realize that this is probably a curtsies issue, but given how tightly related these are, I wanted to first raise the issue here.

**Comment by sebastinas** [comment]
This issue is fixed in at least 0.22.1.
