### ISSUE TITLE
Getting ImportError when I try to run bpython in wsl2 ubuntu 20.04

### ISSUE THREAD

**Issue by Saeedprojects** [bpython/bpython#962]
Bypthon was working fine in wsl ubuntu 20.04 (PowerShell) until I decided to change current python version (3.8) that came with ubuntu 20.04 to python version 3.10.4 following [this YouTube video][1]
now all of a sudden bpython is not working and I get the following error

```
user@userPC:/mnt/c/Users/username$ bpython
Traceback (most recent call last):
  File "/usr/bin/bpython", line 11, in <module>
    load_entry_point('bpython==0.18', 'console_scripts', 'bpython')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 11, in <module>
    import curtsies
  File "/usr/lib/python3/dist-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "/usr/lib/python3/dist-packages/curtsies/window.py", line 11, in <module>
    import blessings
  File "/usr/lib/python3/dist-packages/blessings/__init__.py", line 29, in <module>
    raise ImportError('Blessings needs Python 3.2.3 or greater for Python 3 '
ImportError: Blessings needs Python 3.2.3 or greater for Python 3 support due to http://bugs.python.org/issue10570.
```

The following shows bypthon version
```
user@userPC:/mnt/c/Users/username$ sudo apt-get install bpython
Reading package lists... Done
Building dependency tree
Reading state information... Done
bpython is already the newest version (0.18-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

  [1]: https://www.youtube.com/watch?v=PLgTZqNsMdQ&ab_channel=babarehner

**Comment by fire17** [comment]
@Saeedprojects @sebastinas Hi guys im getting the same error? any chance you know how to solve it?
Ive first installed with `apt install bpython`
i think i will remove it and try to install straight from pip
if i run into this again ill try finding how to get the blessings/curtsies right..

**Comment by fire17** [comment]
Solution!
For anyone else here looking to use bpython over python3.11 or python3.10
You need to remove from apt `sudo apt remove bpython` and reinstall through pip (in the python version you want)
`python3.11 -m pip install bpython`
If you run into the `collections.MutableSet` error, it easy to fix, check out #1008

PS - also on wsl2 currently
