### ISSUE TITLE
AssertionError when typing accentuated characters

### ISSUE THREAD

**Issue by LiteApplication** [bpython/bpython#969]
Bpython crashes when inputting accentuated chars.
```
(python)
Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("é")
é
>>> exit()
(bpython)
bpython version 0.22.1 on top of Python 3.10.6 /usr/bin/python
>>> print("Helllo")
Traceback (most recent call last):
  File "/usr/bin/bpython", line 33, in <module>
    sys.exit(load_entry_point('bpython==0.22.1', 'console_scripts', 'bpython')())
  File "/usr/lib/python3.10/site-packages/bpython/curtsies.py", line 248, in main
    repl.mainloop(True, paste)
  File "/usr/lib/python3.10/site-packages/bpython/curtsies.py", line 181, in mainloop
    self.process_event_and_paint(e)
  File "/usr/lib/python3.10/site-packages/bpython/curtsies.py", line 151, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/lib/python3.10/site-packages/bpython/curtsiesfrontend/repl.py", line 1641, in paint
    assert cursor_row >= 0 and cursor_column >= 0, (
AssertionError: (-1, 271, '>>> print("é', 'print("é', 8)
(zsh) $ echo $?
1
```
That could be due to them being formed with 2 chars in the utf-8 table

**Comment by sebastinas** [comment]
I am unable to reproduce the issue. Does that also happen with an up-to-date `bpython` and `curtsies`?

**Comment by LiteApplication** [comment]
I installed `bpython` today from `pacman` and my Arch Linux installation is less than 48h old.

**Comment by sebastinas** [comment]
The current versions of bpython and curtsies are `0.23` and `0.4.0`, respectively.

**Comment by LiteApplication** [comment]
Oh you were right, the version from pacman isn't up to date, sorry for the unnecessary issue
