### ISSUE TITLE
bpython crashes on ubuntu 22

### ISSUE THREAD

**Issue by gefrag** [bpython/bpython#976]
Hello,

bpython started crashing today, not sure if it is related to any OS packages updates or something, it was working properly.
Please find below anything that could be useful to troubleshoot:

```
bpython
bpython version 0.18 on top of Python 3.8.10 /usr/bin/python3

Traceback (most recent call last):
  File "/usr/bin/bpython", line 11, in <module>
    load_entry_point('bpython==0.18', 'console_scripts', 'bpython')()
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 191, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/lib/python3/dist-packages/bpython/curtsies.py", line 108, in mainloop
    self.initialize_interp()
  File "/usr/lib/python3/dist-packages/bpython/curtsiesfrontend/repl.py", line 1673, in initialize_interp
    del self.coderunner.interp.locals['_Helper']
KeyError: '_Helper'
```

System information:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

Thank you in advance,
George

**Comment by gefrag** [comment]
An update:
It looks like I had bpython installed from apt-get. I uninstalled it and run ```pip install bpython``` and it is now resolved.
