### ISSUE TITLE
MS Windows 10 - asks for termios

### ISSUE THREAD

**Issue by gwd666** [bpython/bpython#978]
Hello, 

I was hoping to manage to get bpython to work on WIN 10. 
I followed the [instructions](https://docs.bpython-interpreter.org/en/latest/windows.html) and `pip` installed `curses-2.2.1+utf8-cp39-cp39-win_amd64.whl` module, played around with `windows-curses` as well, after getting below errors (with same results), and ` pip` installed `bpython-0.23` (into a conda env that has `python 3.9.13` in it) but whenever I run `bpython-curses` in Windows `CMD` prompt (or I also tried the `Git Bash` prompt as an alternative) I end up with 
```
(wdenv)C:\Users\gwd\OneDrive\Documents\dev>bpython-curses
Traceback (most recent call last):
  File "C:\Users\gwd\.conda\envs\wdenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gwd\.conda\envs\wdenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gwd\.conda\envs\wdenv\Scripts\bpython-curses.exe\__main__.py", line 4, in <module>
  File "C:\Users\gwd\.conda\envs\wdenv\lib\site-packages\bpython\cli.py", line 105, in <module>
    from . import args as bpargs
  File "C:\Users\gwd\.conda\envs\wdenv\lib\site-packages\bpython\args.py", line 35, in <module>
    import curtsies
  File "C:\Users\gwd\.conda\envs\wdenv\lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "C:\Users\gwd\.conda\envs\wdenv\lib\site-packages\curtsies\window.py", line 30, in <module>
    from .termhelpers import Cbreak
  File "C:\Users\gwd\.conda\envs\wdenv\lib\site-packages\curtsies\termhelpers.py", line 1, in <module>
    import tty
  File "C:\Users\gwd\.conda\envs\wdenv\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```
Afaik `termios` is Linux only, right? My guess was that the `curses` module would handle that type of call? 
What am  doing wrong here - any idea?

**Comment by Code4SAFrankie** [comment]
I still have this issue. Just installed on python-3.9.10.amd64

**Comment by sebastinas** [comment]
Try `bpython-curses` instead.

**Comment by Andrej730** [comment]
Installing curses from https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses and running `bpython-curses` worked, thank you!
