### ISSUE TITLE
bpython fails to start on arm64 with python 3.10.10

### ISSUE THREAD

**Issue by bram2000** [bpython/bpython#990]
Hello,

I'm having some issues getting `bpython` to run in my python 3.10.10 project on arm64 (apple M1).

I can reproduce easily by creating a brand new 3.10.10 virtualenv, activating, running `pip install bpython`.

If I now try to run `bpython`, I get the following error:

`❯ bpython
Traceback (most recent call last):
  File "/private/tmp/bpython-test/venv/bin/bpython", line 5, in <module>
    from bpython.curtsies import main
  File "/private/tmp/bpython-test/venv/lib/python3.10/site-packages/bpython/curtsies.py", line 10, in <module>
    import curtsies
  File "/private/tmp/bpython-test/venv/lib/python3.10/site-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "/private/tmp/bpython-test/venv/lib/python3.10/site-packages/curtsies/window.py", line 28, in <module>
    from .formatstring import fmtstr, FmtStr
  File "/private/tmp/bpython-test/venv/lib/python3.10/site-packages/curtsies/formatstring.py", line 23, in <module>
    from cwcwidth import wcswidth, wcwidth
  File "/private/tmp/bpython-test/venv/lib/python3.10/site-packages/cwcwidth/__init__.py", line 32, in <module>
    from ._impl import wcwidth, wcswidth
ImportError: dlopen(/private/tmp/bpython-test/venv/lib/python3.10/site-packages/cwcwidth/_impl.cpython-310-darwin.so, 0x0002): tried: '/private/tmp/bpython-test/venv/lib/python3.10/site-packages/cwcwidth/_impl.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/bpython-test/venv/lib/python3.10/site-packages/cwcwidth/_impl.cpython-310-darwin.so' (no such file), '/private/tmp/bpython-test/venv/lib/python3.10/site-packages/cwcwidth/_impl.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

Seems possibly related to #945

**Comment by bram2000** [comment]
I think I've resolved this by removing my virtual env, running `pip cache purge` and then re-installing dependencies.

**Comment by sebastinas** [comment]
pip being odd again. Sorry for the inconvenience.
